/// Autonomous agent flows and Microsoft 365 agent flows registered in the tenant.
table AgentFlow
	lineageTag: f73bc3b2-9acb-4c2b-a8b6-7ce9780fc898

	column FlowId
		dataType: string
		isHidden
		lineageTag: 570f4f06-df35-4349-bb4f-07db52bd327a
		summarizeBy: none
		sourceColumn: FlowId

	column FlowName
		dataType: string
		lineageTag: 6df8b564-bdd9-46dc-89c3-ca01063756dd
		summarizeBy: none
		sourceColumn: FlowName

	column FlowType
		dataType: string
		lineageTag: 0e40e448-4449-4081-a102-71a8eeef2751
		summarizeBy: none
		sourceColumn: FlowType

	column EnvironmentId
		dataType: string
		isHidden
		lineageTag: 14327c46-2334-4948-b599-10864d39c687
		summarizeBy: none
		sourceColumn: EnvironmentId

	column State
		dataType: string
		lineageTag: 775ac6bd-64b6-460c-9b90-b602de8c8be9
		summarizeBy: none
		sourceColumn: State

	column CreatedAt
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: 167fcde4-1825-4429-8489-a7f74a86e817
		summarizeBy: none
		sourceColumn: CreatedAt

	column Region
		dataType: string
		lineageTag: 14f03e41-af0a-4c72-8ed7-f472e5e4a6d3
		summarizeBy: none
		sourceColumn: Region

	column LastUsed
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: d0e588e6-7e94-457f-8896-eafe77ab9328
		summarizeBy: none
		sourceColumn: LastUsed

	partition AgentFlow = m
		mode: import
		source =
				let
				    Raw = FnArg("PowerPlatformResources | where type in~ ('microsoft.powerautomate/agentflows','microsoft.powerautomate/m365agentflows') | extend p = properties | project FlowId = tostring(name), FlowName = tostring(p.displayName), FlowType = iff(type has 'm365agentflows', 'M365 Agent Flow', 'Agent Flow'), EnvironmentId = tostring(p.environmentId), State = tostring(p.state), CreatedAt = tostring(p.createdAt), Region = tostring(location) | order by FlowId asc"),
				    Usage = FnArg("PowerPlatformResources | where type =~ 'microsoft.powerplatformusage/usagerecords' | where isnotnull(properties) | project ResourceKey = tostring(properties.resourceId), LastUsedRaw = tostring(properties.lastUsed) | where isnotempty(ResourceKey) and isnotempty(LastUsedRaw) | summarize LastUsedRaw = max(LastUsedRaw) by ResourceKey | order by ResourceKey asc"),
				    tF = FnRecordsToTable(Raw, {"FlowId", "FlowName", "FlowType", "EnvironmentId", "State", "CreatedAt", "Region"}),
				    tU = FnRecordsToTable(Usage, {"ResourceKey", "LastUsedRaw"}),
				    Joined = Table.NestedJoin(tF, {"FlowId"}, tU, {"ResourceKey"}, "u", JoinKind.LeftOuter),
				    Expanded = Table.ExpandTableColumn(Joined, "u", {"LastUsedRaw"}, {"LastUsedRaw"}),
				    WithUse = Table.AddColumn(Expanded, "LastUsed", each FnToDateTime([LastUsedRaw]), type datetime),
				    Kept = Table.SelectColumns(WithUse, {"FlowId", "FlowName", "FlowType", "EnvironmentId", "State", "CreatedAt", "Region", "LastUsed"}, MissingField.UseNull),
				    Converted = Table.TransformColumns(Kept, {{"CreatedAt", FnToDateTime, type datetime}}),
				    Final = Table.TransformColumnTypes(Converted, {{"FlowId", type text}, {"FlowName", type text}, {"FlowType", type text}, {"EnvironmentId", type text}, {"State", type text}, {"Region", type text}})
				in
				    Final

