/// One row per agent-to-connector binding, including MCP server tools.
table AgentConnector
	lineageTag: 98fecf52-ee2a-467a-9eed-273aa5ca4424

	column AgentKey
		dataType: string
		isHidden
		lineageTag: ff9c5048-315d-43a9-a073-54fa0c7111df
		summarizeBy: none
		sourceColumn: AgentKey

	column ConnectorId
		dataType: string
		lineageTag: 1ef5e1a8-e73e-435c-9a5a-217f243a886d
		summarizeBy: none
		sourceColumn: ConnectorId

	column OperationCount
		dataType: int64
		formatString: #,0
		lineageTag: 19964511-4d6c-47df-9c45-9d03eda96fb2
		summarizeBy: sum
		sourceColumn: OperationCount

	/// TRUE when the connector operation list advertises an MCP server tool.
	column IsMcpServer
		dataType: boolean
		lineageTag: 919af040-6ed2-4850-88ca-bc87f889f626
		summarizeBy: none
		sourceColumn: IsMcpServer

	partition AgentConnector = m
		mode: import
		source =
				let
				    Raw = FnArg("PowerPlatformResources | where type =~ 'microsoft.copilotstudio/agents' | extend p = properties | mv-expand conn = p.powerPlatformConnectors | where isnotnull(conn) | project AgentKey = strcat(tostring(p.environmentId), '|', tostring(name)), ConnectorId = tostring(conn.connectorId), OperationCount = coalesce(array_length(conn.operations), 0), IsMcpServer = tostring(conn.operations) contains '""type"":""MCP""' | order by AgentKey asc, ConnectorId asc, OperationCount asc, IsMcpServer asc"),
				    Kept = FnRecordsToTable(Raw, {"AgentKey", "ConnectorId", "OperationCount", "IsMcpServer"}),
				    Converted = Table.TransformColumns(Kept, {{"OperationCount", FnToInt, Int64.Type}, {"IsMcpServer", FnToBool, type logical}}),
				    Final = Table.TransformColumnTypes(Converted, {{"AgentKey", type text}, {"ConnectorId", type text}})
				in
				    Final

