/// Every Copilot Studio and Microsoft 365 Copilot Agent Builder agent in the tenant, sourced from the Power Platform inventory exposed through Azure Resource Graph.
table Agent
	lineageTag: c82b1b35-75eb-43a6-90ec-15180230321b

	/// Unique agent identifier: environment id + agent id. Microsoft's pre-installed first-party agents reuse the same agent id in every environment, so the environment must be part of the key.
	column AgentKey
		dataType: string
		isHidden
		lineageTag: 03b2e51d-1290-49fb-8b15-759ca423861c
		summarizeBy: none
		sourceColumn: AgentKey

	/// Raw agent (bot) identifier from the Power Platform inventory. Not unique across environments for first-party agents.
	column AgentId
		dataType: string
		isHidden
		lineageTag: 39d4adc6-ec5b-470b-ab07-1f22bfcd2390
		summarizeBy: none
		sourceColumn: AgentId

	/// Display name of the agent.
	column AgentName
		dataType: string
		lineageTag: f17d1230-f2f2-4fc4-9cfb-659cb071864e
		summarizeBy: none
		sourceColumn: AgentName

	/// Normalised authoring platform: Copilot Studio, M365 Copilot Agent Builder or Azure AI Foundry.
	column Platform
		dataType: string
		lineageTag: db6bd246-6e32-4bbb-abdb-d87413bb371b
		summarizeBy: none
		sourceColumn: Platform

	/// Raw createdIn value reported by the Power Platform inventory API.
	column AuthoringSurface
		dataType: string
		lineageTag: 5bdcd00c-8910-4db4-bcf6-9d001b84747f
		summarizeBy: none
		sourceColumn: AuthoringSurface

	column EnvironmentId
		dataType: string
		isHidden
		lineageTag: a1acc6b3-7f50-4621-ab7b-a7ff9e18da8f
		summarizeBy: none
		sourceColumn: EnvironmentId

	column EnvironmentName
		dataType: string
		lineageTag: b8eb3c36-655d-49ee-90f5-b07da2b75e1c
		summarizeBy: none
		sourceColumn: EnvironmentName

	column EnvironmentType
		dataType: string
		lineageTag: cf8198b9-dbac-4703-a042-6d56f0f98dbd
		summarizeBy: none
		sourceColumn: EnvironmentType

	column Region
		dataType: string
		lineageTag: cad5c541-dae7-4ffd-a343-03d8ce877142
		summarizeBy: none
		sourceColumn: Region

	column SchemaName
		dataType: string
		isHidden
		lineageTag: bfc774b5-41f3-4e9a-89b1-48804fe1987f
		summarizeBy: none
		sourceColumn: SchemaName

	/// Generative (AI orchestration) or Classic (topic driven).
	column Orchestration
		dataType: string
		lineageTag: 01faa087-861d-47ab-8fe4-dc19fdc1d94f
		summarizeBy: none
		sourceColumn: Orchestration

	/// Underlying LLM the agent is configured to use.
	column Model
		dataType: string
		lineageTag: 7156286b-3c26-4e23-affa-b75eae4d50a9
		summarizeBy: none
		sourceColumn: Model

	/// Authentication mode. 'None' means anonymous end-user access.
	column Authentication
		dataType: string
		lineageTag: 19196e67-16ec-4392-82da-752254bc9085
		summarizeBy: none
		sourceColumn: Authentication

	column CreatedAt
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: 784a245e-bdbb-48cd-b137-1e99e3c421b8
		summarizeBy: none
		sourceColumn: CreatedAt

	column LastPublishedAt
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: d5fef3a8-51dd-413d-974c-6d7194de7137
		summarizeBy: none
		sourceColumn: LastPublishedAt

	/// Latest usage signal from Power Platform usage records.
	column LastUsed
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: 2ba60b3e-a0d7-4f31-99ca-2a425a123356
		summarizeBy: none
		sourceColumn: LastUsed

	column IsPublished
		dataType: boolean
		lineageTag: 3c349080-d110-46ce-863a-4bf19da0f261
		summarizeBy: none
		sourceColumn: IsPublished

	column IsQuarantined
		dataType: boolean
		lineageTag: f9e62b9b-7989-49f4-8c4c-559ef2ae9559
		summarizeBy: none
		sourceColumn: IsQuarantined

	column IsManaged
		dataType: boolean
		lineageTag: b5966bd3-87b7-4abc-ac3e-86ff0edd4291
		summarizeBy: none
		sourceColumn: IsManaged

	column IsGithubCopilotAgent
		dataType: boolean
		lineageTag: 4a617e78-69d9-4aae-bacc-c3920a78f6cf
		summarizeBy: none
		sourceColumn: IsGithubCopilotAgent

	column IsCLIAgent
		dataType: boolean
		lineageTag: fb2c086d-ccbe-4c86-a1e8-2b42013e5e6c
		summarizeBy: none
		sourceColumn: IsCLIAgent

	column WebSearchEnabled
		dataType: boolean
		lineageTag: bda01f67-d178-44d0-b194-755fb4b5bb56
		summarizeBy: none
		sourceColumn: WebSearchEnabled

	column Channels
		dataType: string
		lineageTag: 3b196913-45df-4269-9c98-eb4196cd9928
		summarizeBy: none
		sourceColumn: Channels

	column ChannelCount
		dataType: int64
		formatString: #,0
		lineageTag: da43a82b-2098-4ad7-934c-02105073c377
		summarizeBy: sum
		sourceColumn: ChannelCount

	column TopicCount
		dataType: int64
		formatString: #,0
		lineageTag: 1a487d63-e1ea-4585-82d5-17536a0931a8
		summarizeBy: sum
		sourceColumn: TopicCount

	column ToolCount
		dataType: int64
		formatString: #,0
		lineageTag: 39c3765a-0c1e-4a6e-b2ed-c4837c1beb94
		summarizeBy: sum
		sourceColumn: ToolCount

	column KnowledgeCount
		dataType: int64
		formatString: #,0
		lineageTag: 26b2849a-b2ee-4077-b66a-1736d2e62df3
		summarizeBy: sum
		sourceColumn: KnowledgeCount

	column ConnectedAgentCount
		dataType: int64
		formatString: #,0
		lineageTag: b22fda5d-6584-4928-811a-445f6d5bd491
		summarizeBy: sum
		sourceColumn: ConnectedAgentCount

	column ConnectorCount
		dataType: int64
		formatString: #,0
		lineageTag: 131a6028-4bdf-4388-9797-f65f69f28b31
		summarizeBy: sum
		sourceColumn: ConnectorCount

	column ConnectorOpsCount
		dataType: int64
		formatString: #,0
		lineageTag: 8e6b5afe-ff82-41df-bc95-720700dfad18
		summarizeBy: sum
		sourceColumn: ConnectorOpsCount

	column FlowCount
		dataType: int64
		formatString: #,0
		lineageTag: ac617e79-d2a0-4151-b178-7534b2f8157b
		summarizeBy: sum
		sourceColumn: FlowCount

	column SharedUserCount
		dataType: int64
		formatString: #,0
		lineageTag: 56410741-c6fe-4963-9838-1850f9d343fd
		summarizeBy: sum
		sourceColumn: SharedUserCount

	column SharedGroupCount
		dataType: int64
		formatString: #,0
		lineageTag: 6f9df346-c829-43e2-b692-c679c222ff90
		summarizeBy: sum
		sourceColumn: SharedGroupCount

	/// TRUE when the agent is shared with everyone in the tenant.
	column SharedTenantWide
		dataType: boolean
		lineageTag: bc0b4817-c823-47ae-9315-6f9f341fdaf2
		summarizeBy: none
		sourceColumn: SharedTenantWide

	column EditorUserCount
		dataType: int64
		formatString: #,0
		lineageTag: 528ed278-72de-4d17-bf87-4803ccfe82dd
		summarizeBy: sum
		sourceColumn: EditorUserCount

	column OwnerId
		dataType: string
		isHidden
		lineageTag: 57fb3284-3659-4181-a74e-a1878f769125
		summarizeBy: none
		sourceColumn: OwnerId

	column CreatedBy
		dataType: string
		isHidden
		lineageTag: d6177864-ee86-4dcb-bac5-a55f45e8bf67
		summarizeBy: none
		sourceColumn: CreatedBy

	/// Display name of the agent's creator, resolved from Entra ID via Microsoft Graph directoryObjects/getByIds.
	column CreatedByName = LOOKUPVALUE ( 'User'[DisplayName], 'User'[UserKey], 'Agent'[CreatedBy] )
		dataType: string
		lineageTag: 23e17b23-4847-454e-8619-14cd339312f4
		summarizeBy: none

	/// Display name of the agent's current owner.
	column OwnerName = RELATED ( 'User'[DisplayName] )
		dataType: string
		lineageTag: b729fd84-aa7b-409f-ac57-d439d12392ac
		summarizeBy: none

	/// User principal name of the owner, where the identity resolved to a user.
	column OwnerUpn = RELATED ( 'User'[UserPrincipalName] )
		dataType: string
		lineageTag: 59176a4c-956c-4086-a82b-80339a0ea23c
		summarizeBy: none

	column EntraAppId
		dataType: string
		isHidden
		lineageTag: 7925d365-fea0-405c-991d-7c7be475f0ee
		summarizeBy: none
		sourceColumn: EntraAppId

	column TitleId
		dataType: string
		isHidden
		lineageTag: 4b29ba2f-9a21-444b-a5d1-fc76a838a601
		summarizeBy: none
		sourceColumn: TitleId

	column DaysSinceLastUse
		dataType: int64
		formatString: #,0
		lineageTag: b40e9ae4-21cb-4071-bead-eb52147b48d1
		summarizeBy: sum
		sourceColumn: DaysSinceLastUse

	column AgeDays
		dataType: int64
		formatString: #,0
		lineageTag: d849eddf-5a78-4e97-a443-6a702d0b18e9
		summarizeBy: sum
		sourceColumn: AgeDays

	column CreatedMonth
		dataType: string
		lineageTag: a07f393d-a469-4b92-baac-c53e3fc4f57f
		summarizeBy: none
		sourceColumn: CreatedMonth

	/// Active (7d) / Active (30d) / Idle (90d) / Dormant (90d+) / No usage signal.
	column ActivityStatus
		dataType: string
		lineageTag: a5a51810-1be8-431e-af78-4109689aa0e6
		summarizeBy: none
		sourceColumn: ActivityStatus

	/// Heuristic governance risk score (0-11).
	column RiskScore
		dataType: int64
		formatString: #,0
		lineageTag: 259a2687-87d6-40f5-983f-f6936b0f2807
		summarizeBy: sum
		sourceColumn: RiskScore

	/// Low (<3), Medium (3-4), High (5+).
	column RiskBand
		dataType: string
		lineageTag: 51399d50-9431-42a4-b082-3ebf26fd8de0
		summarizeBy: none
		sourceColumn: RiskBand

	/// How many individual risk factors fired for this agent.
	column RiskFactorCount
		dataType: int64
		formatString: #,0
		lineageTag: 420f898e-9e0e-44c9-b6d4-25f13c6a527f
		summarizeBy: sum
		sourceColumn: RiskFactorCount

	/// Human-readable list of every risk factor that contributed to the score, with its point value.
	column RiskReasons
		dataType: string
		lineageTag: 54cfb9aa-ee74-44bf-8f87-3e91a717d2b5
		summarizeBy: none
		sourceColumn: RiskReasons

	column CreatedDate
		dataType: dateTime
		isHidden
		formatString: yyyy-mm-dd
		lineageTag: e5713a33-037f-41b4-a3f4-4dde6cd539be
		summarizeBy: none
		sourceColumn: CreatedDate

		annotation UnderlyingDateTimeDataType = Date

	column LastUsedDate
		dataType: dateTime
		isHidden
		formatString: yyyy-mm-dd
		lineageTag: 1a67bc91-17c8-45a4-af62-2f682f285a2c
		summarizeBy: none
		sourceColumn: LastUsedDate

		annotation UnderlyingDateTimeDataType = Date

	/// What kind of principal owns the agent. Agents whose owner id does not resolve to a directory object - deleted users, cross-tenant guests, or system identities Graph will not return - are labelled rather than left blank.
	column OwnerPrincipalType = VAR p = RELATED ( 'User'[PrincipalType] ) RETURN IF ( ISBLANK ( p ) || p = "", "Not resolved in Entra", p )
		dataType: string
		lineageTag: a2cbe4be-df30-49e5-98cc-81f749aca74c
		summarizeBy: none

	/// Whether a person authored the agent, the platform provisioned it automatically, or no creator was recorded at all. Most tenants are dominated by platform-provisioned agents - default environment scaffolding, template copies and system bots - which drown out real human activity, so this is offered as a slicer on every page. Note that a DAX text column read from CSV holds an empty string rather than BLANK, so both must be tested.
	column AgentOrigin = VAR creator = 'Agent'[CreatedByName] RETURN IF ( ISBLANK ( creator ) || creator = "", "Creator unknown", IF ( creator = "System / platform", "Platform-provisioned", "Human-built" ) )
		dataType: string
		lineageTag: 3e38618f-eef9-49e1-85f5-3ae8f7c0f86f
		summarizeBy: none

	partition Agent = m
		mode: import
		source =
				let
				    RawAgents = FnArg("PowerPlatformResources | where type =~ 'microsoft.copilotstudio/agents' | extend p = properties | extend cc = p.componentsCounts, cap = p.capabilitiesCounts, sv = p.sharedWithViewers, se = p.sharedWithEditors | project AgentKey = strcat(tostring(p.environmentId), '|', tostring(name)), AgentId = tostring(name), AgentName = tostring(p.displayName), AuthoringSurface = tostring(p.createdIn), EnvironmentId = tostring(p.environmentId), Region = tostring(location), SchemaName = tostring(p.schemaName), Orchestration = tostring(p.orchestration), Model = tostring(p.model), Authentication = tostring(p.authentication), CreatedAt = tostring(p.createdAt), LastPublishedAt = tostring(p.lastPublishedAt), IsQuarantined = tobool(p.isQuarantined), IsManaged = tobool(p.isManaged), IsGithubCopilotAgent = tobool(p.isGithubCopilotAgent), IsCLIAgent = tobool(p.isCLIAgent), WebSearchEnabled = tobool(p.isWebSearchEnabledForKnowledge), Channels = strcat_array(p.channels, '; '), ChannelCount = coalesce(array_length(p.channels), 0), TopicCount = toint(cc.topics), ToolCount = toint(cc.tools), KnowledgeCount = toint(cc.knowledge), ConnectedAgentCount = toint(cc.connectedAgents), ConnectorCount = toint(cap.distinctPowerPlatformConnectors), ConnectorOpsCount = toint(cap.distinctPowerPlatformConnectorsOperations), FlowCount = toint(cap.distinctFlows), SharedUserCount = toint(sv.userCount), SharedGroupCount = toint(sv.groupCount), SharedTenantWide = tobool(sv.entireTenant), EditorUserCount = toint(se.userCount), OwnerId = tostring(p.ownerId), CreatedBy = tostring(p.createdBy), EntraAppId = tostring(p.entraAppId), TitleId = tostring(p.titleId) | order by AgentKey asc"),
				    RawUsage = FnArg("PowerPlatformResources | where type =~ 'microsoft.powerplatformusage/usagerecords' | where isnotnull(properties) | project ResourceKey = tostring(properties.resourceId), LastUsedRaw = tostring(properties.lastUsed) | where isnotempty(ResourceKey) and isnotempty(LastUsedRaw) | summarize LastUsedRaw = max(LastUsedRaw) by ResourceKey | order by ResourceKey asc"),
				    RawEnvs = FnArg("PowerPlatformResources | where type =~ 'microsoft.powerplatform/environments' | extend p = properties | project EnvironmentId = tostring(name), EnvironmentName = tostring(p.displayName), Region = tostring(location), EnvironmentType = tostring(p.environmentType), IsManaged = tobool(p.isManaged), EnvironmentGroupId = tostring(p.environmentGroupId), CreatedAt = tostring(p.createdAt), LastModifiedAt = tostring(p.lastModifiedAt), CreatedBy = tostring(p.createdBy) | order by EnvironmentId asc"),
				    tAgents = FnRecordsToTable(RawAgents, {"AgentKey", "AgentId", "AgentName", "AuthoringSurface", "EnvironmentId", "Region", "SchemaName", "Orchestration", "Model", "Authentication", "CreatedAt", "LastPublishedAt", "IsQuarantined", "IsManaged", "IsGithubCopilotAgent", "IsCLIAgent", "WebSearchEnabled", "Channels", "ChannelCount", "TopicCount", "ToolCount", "KnowledgeCount", "ConnectedAgentCount", "ConnectorCount", "ConnectorOpsCount", "FlowCount", "SharedUserCount", "SharedGroupCount", "SharedTenantWide", "EditorUserCount", "OwnerId", "CreatedBy", "EntraAppId", "TitleId"}),
				    tUsage = FnRecordsToTable(RawUsage, {"ResourceKey", "LastUsedRaw"}),
				    tEnvs = FnRecordsToTable(RawEnvs, {"EnvironmentId", "EnvironmentName", "EnvironmentType"}),
				    JoinUsage = Table.NestedJoin(tAgents, {"AgentId"}, tUsage, {"ResourceKey"}, "u", JoinKind.LeftOuter),
				    ExpUsage = Table.ExpandTableColumn(JoinUsage, "u", {"LastUsedRaw"}, {"LastUsedRaw"}),
				    JoinEnv = Table.NestedJoin(ExpUsage, {"EnvironmentId"}, tEnvs, {"EnvironmentId"}, "e", JoinKind.LeftOuter),
				    ExpEnv = Table.ExpandTableColumn(JoinEnv, "e", {"EnvironmentName", "EnvironmentType"}, {"EnvironmentName", "EnvironmentType"}),
				    Converted = Table.TransformColumns(ExpEnv, {{"CreatedAt", FnToDateTime, type datetime}, {"LastPublishedAt", FnToDateTime, type datetime}, {"LastUsedRaw", FnToDateTime, type datetime}}),
				    Bools = Table.TransformColumns(Converted, {{"IsQuarantined", FnToLogical, type logical}, {"IsManaged", FnToLogical, type logical}, {"IsGithubCopilotAgent", FnToLogical, type logical}, {"IsCLIAgent", FnToLogical, type logical}, {"WebSearchEnabled", FnToLogical, type logical}, {"SharedTenantWide", FnToLogical, type logical}}),
				    Renamed = Table.RenameColumns(Bools, {{"LastUsedRaw", "LastUsed"}}),
				    Typed = Table.TransformColumnTypes(Renamed, {{"EnvironmentName", type text}, {"EnvironmentType", type text}}),
				    RawFoundry = FnArg("resources | where type startswith 'microsoft.cognitiveservices' or type startswith 'microsoft.machinelearningservices' | where (type endswith 'accounts/projects') or (tostring(kind) == 'Project') | extend p = properties | project AgentKey = tostring(id), AgentId = tostring(id), AgentName = tostring(split(name, '/')[-1]), EnvironmentId = tostring(subscriptionId), EnvironmentName = iff(name has '/', tostring(split(name, '/')[0]), tostring(name)), Region = tostring(location), CreatedAt = tostring(p.createdAtDate) | order by AgentKey asc"),
				    FoundryRecords = List.Transform(RawFoundry, each [
				        AgentKey = Record.FieldOrDefault(_, "AgentKey", null),
				        AgentId = Record.FieldOrDefault(_, "AgentId", null),
				        AgentName = Record.FieldOrDefault(_, "AgentName", null),
				        AuthoringSurface = "Azure AI Foundry",
				        EnvironmentId = Record.FieldOrDefault(_, "EnvironmentId", null),
				        Region = Record.FieldOrDefault(_, "Region", null),
				        SchemaName = null,
				        Orchestration = "Generative",
				        Model = "See deployments",
				        Authentication = "Microsoft Entra",
				        CreatedAt = FnToDateTime(Record.FieldOrDefault(_, "CreatedAt", null)),
				        LastPublishedAt = null,
				        IsQuarantined = false,
				        IsManaged = true,
				        IsGithubCopilotAgent = false,
				        IsCLIAgent = false,
				        WebSearchEnabled = false,
				        Channels = "API / SDK",
				        ChannelCount = 1,
				        TopicCount = 0,
				        ToolCount = 0,
				        KnowledgeCount = 0,
				        ConnectedAgentCount = 0,
				        ConnectorCount = 0,
				        ConnectorOpsCount = 0,
				        FlowCount = 0,
				        SharedUserCount = 0,
				        SharedGroupCount = 0,
				        SharedTenantWide = false,
				        EditorUserCount = 0,
				        OwnerId = null,
				        CreatedBy = null,
				        EntraAppId = null,
				        TitleId = null,
				        LastUsed = null,
				        EnvironmentName = Record.FieldOrDefault(_, "EnvironmentName", null),
				        EnvironmentType = "Azure subscription"
				    ]),
				    tFoundry = FnRecordsToTable(FoundryRecords, {"AgentKey", "AgentId", "AgentName", "AuthoringSurface", "EnvironmentId", "Region", "SchemaName", "Orchestration", "Model", "Authentication", "CreatedAt", "LastPublishedAt", "IsQuarantined", "IsManaged", "IsGithubCopilotAgent", "IsCLIAgent", "WebSearchEnabled", "Channels", "ChannelCount", "TopicCount", "ToolCount", "KnowledgeCount", "ConnectedAgentCount", "ConnectorCount", "ConnectorOpsCount", "FlowCount", "SharedUserCount", "SharedGroupCount", "SharedTenantWide", "EditorUserCount", "OwnerId", "CreatedBy", "EntraAppId", "TitleId", "LastUsed", "EnvironmentName", "EnvironmentType"}),
				    Combined = Table.Combine({Typed, tFoundry}),
				    Unified = FnDistinctKey(Combined, "AgentKey"),
				    Today = DateTime.LocalNow(),
				    WithPlatform = Table.AddColumn(Unified, "Platform", each
				        if [AuthoringSurface] = "Copilot Studio Lite" then "M365 Copilot Agent Builder"
				        else if [AuthoringSurface] = null or [AuthoringSurface] = "" then "Copilot Studio"
				        else [AuthoringSurface], type text),
				    WithPub = Table.AddColumn(WithPlatform, "IsPublished", each [LastPublishedAt] <> null, type logical),
				    WithDays = Table.AddColumn(WithPub, "DaysSinceLastUse", each if [LastUsed] = null then null else Duration.Days(Today - [LastUsed]), Int64.Type),
				    WithAge = Table.AddColumn(WithDays, "AgeDays", each if [CreatedAt] = null then null else Duration.Days(Today - [CreatedAt]), Int64.Type),
				    WithMonth = Table.AddColumn(WithAge, "CreatedMonth", each if [CreatedAt] = null then null else Date.ToText(DateTime.Date([CreatedAt]), "yyyy-MM"), type text),
				    WithStatus = Table.AddColumn(WithMonth, "ActivityStatus", each
				        if [DaysSinceLastUse] = null then "No usage signal"
				        else if [DaysSinceLastUse] <= 7 then "Active (7d)"
				        else if [DaysSinceLastUse] <= 30 then "Active (30d)"
				        else if [DaysSinceLastUse] <= 90 then "Idle (90d)"
				        else "Dormant (90d+)", type text),
				    WithRiskList = Table.AddColumn(WithStatus, "RiskFactorList", each List.RemoveNulls({
				        (if [Authentication] = null or [Authentication] = "" or [Authentication] = "None" or [Authentication] = "No authentication" then "No authentication configured (+3)" else null),
				        (if [IsQuarantined] = true then "Agent is quarantined (+3)" else null),
				        (if [SharedTenantWide] = true then "Shared with the entire tenant (+2)" else null),
				        (if [SharedTenantWide] = true and [LastUsed] = null then "Shared tenant-wide and never used (+1)" else null),
				        (if [WebSearchEnabled] = true then "Web search enabled on knowledge (+1)" else null),
				        (if [ConnectorCount] <> null and [ConnectorCount] > 0 then "Uses one or more connectors (+1)" else null),
				        (if [ConnectedAgentCount] <> null and [ConnectedAgentCount] > 0 then "Connected to other agents (+1)" else null)
				    }), type list),
				    WithReasons = Table.AddColumn(WithRiskList, "RiskReasons", each if List.Count([RiskFactorList]) = 0 then "No risk factors detected" else Text.Combine([RiskFactorList], "; "), type text),
				    WithFactorCount = Table.AddColumn(WithReasons, "RiskFactorCount", each List.Count([RiskFactorList]), Int64.Type),
				    WithRisk = Table.AddColumn(WithFactorCount, "RiskScore", each
				        (if [SharedTenantWide] = true then 2 else 0)
				        + (if [IsQuarantined] = true then 3 else 0)
				        + (if [Authentication] = null or [Authentication] = "" or [Authentication] = "None" or [Authentication] = "No authentication" then 3 else 0)
				        + (if [WebSearchEnabled] = true then 1 else 0)
				        + (if [ConnectorCount] <> null and [ConnectorCount] > 0 then 1 else 0)
				        + (if [ConnectedAgentCount] <> null and [ConnectedAgentCount] > 0 then 1 else 0)
				        + (if [SharedTenantWide] = true and [LastUsed] = null then 1 else 0), Int64.Type),
				    WithBand = Table.AddColumn(WithRisk, "RiskBand", each if [RiskScore] >= 5 then "High" else if [RiskScore] >= 3 then "Medium" else "Low", type text),
				    Ordered = Table.SelectColumns(WithBand, {"AgentKey", "AgentId", "AgentName", "Platform", "AuthoringSurface", "EnvironmentId", "EnvironmentName", "EnvironmentType", "Region", "SchemaName", "Orchestration", "Model", "Authentication", "CreatedAt", "LastPublishedAt", "LastUsed", "IsPublished", "IsQuarantined", "IsManaged", "IsGithubCopilotAgent", "IsCLIAgent", "WebSearchEnabled", "Channels", "ChannelCount", "TopicCount", "ToolCount", "KnowledgeCount", "ConnectedAgentCount", "ConnectorCount", "ConnectorOpsCount", "FlowCount", "SharedUserCount", "SharedGroupCount", "SharedTenantWide", "EditorUserCount", "OwnerId", "CreatedBy", "EntraAppId", "TitleId", "DaysSinceLastUse", "AgeDays", "CreatedMonth", "ActivityStatus", "RiskScore", "RiskBand", "RiskFactorCount", "RiskReasons"}, MissingField.UseNull),
				    Retyped = Table.TransformColumnTypes(Ordered, {{"AgentKey", type text}, {"AgentId", type text}, {"AgentName", type text}, {"Platform", type text}, {"AuthoringSurface", type text}, {"EnvironmentId", type text}, {"EnvironmentName", type text}, {"EnvironmentType", type text}, {"Region", type text}, {"SchemaName", type text}, {"Orchestration", type text}, {"Model", type text}, {"Authentication", type text}, {"CreatedAt", type datetime}, {"LastPublishedAt", type datetime}, {"LastUsed", type datetime}, {"IsPublished", type logical}, {"IsQuarantined", type logical}, {"IsManaged", type logical}, {"IsGithubCopilotAgent", type logical}, {"IsCLIAgent", type logical}, {"WebSearchEnabled", type logical}, {"Channels", type text}, {"ChannelCount", Int64.Type}, {"TopicCount", Int64.Type}, {"ToolCount", Int64.Type}, {"KnowledgeCount", Int64.Type}, {"ConnectedAgentCount", Int64.Type}, {"ConnectorCount", Int64.Type}, {"ConnectorOpsCount", Int64.Type}, {"FlowCount", Int64.Type}, {"SharedUserCount", Int64.Type}, {"SharedGroupCount", Int64.Type}, {"SharedTenantWide", type logical}, {"EditorUserCount", Int64.Type}, {"OwnerId", type text}, {"CreatedBy", type text}, {"EntraAppId", type text}, {"TitleId", type text}, {"DaysSinceLastUse", Int64.Type}, {"AgeDays", Int64.Type}, {"CreatedMonth", type text}, {"ActivityStatus", type text}, {"RiskScore", Int64.Type}, {"RiskBand", type text}, {"RiskFactorCount", Int64.Type}, {"RiskReasons", type text}}),
				    WithCreatedDate = Table.AddColumn(Retyped, "CreatedDate", each if [CreatedAt] = null then null else DateTime.Date([CreatedAt]), type date),
				    WithLastUsedDate = Table.AddColumn(WithCreatedDate, "LastUsedDate", each if [LastUsed] = null then null else DateTime.Date([LastUsed]), type date)
				in
				    WithLastUsedDate

	annotation PBI_ResultType = Table

