/// Azure AI Foundry accounts, hubs and projects - the surface that hosts Foundry Agent Service agents.
table AzureAIResource
	lineageTag: 4fa4fe89-65cb-4ed8-93b9-f5f8c14280c6

	column ResourceId
		dataType: string
		isHidden
		lineageTag: 12c07c29-c843-4fed-83c4-b72ca046d3c4
		summarizeBy: none
		sourceColumn: ResourceId

	column ResourceName
		dataType: string
		lineageTag: 61a636ad-5598-4601-9ff3-43a8bc7423df
		summarizeBy: none
		sourceColumn: ResourceName

	column ParentAccount
		dataType: string
		lineageTag: a99090e2-9afa-46ca-b93a-4359004b2c09
		summarizeBy: none
		sourceColumn: ParentAccount

	column ResourceType
		dataType: string
		lineageTag: bc1372c6-41ec-4d80-84ad-62d6ce6332b0
		summarizeBy: none
		sourceColumn: ResourceType

	column Kind
		dataType: string
		lineageTag: b63f3095-0a4c-48c2-a1eb-e529cb2539f1
		summarizeBy: none
		sourceColumn: Kind

	/// Foundry project / AI Foundry account / Foundry hub / Azure OpenAI.
	column Category
		dataType: string
		lineageTag: 8debda05-9758-4b3e-bd99-32ff0ff14ee4
		summarizeBy: none
		sourceColumn: Category

	/// TRUE for Foundry projects, which are the resources that host Foundry Agent Service agents.
	column IsAgentHost
		dataType: boolean
		lineageTag: fafe27d0-9537-448a-a7b5-4a05d239aacb
		summarizeBy: none
		sourceColumn: IsAgentHost

	column Region
		dataType: string
		lineageTag: a8352d79-4e51-430e-ae79-b2c2dd9fb05e
		summarizeBy: none
		sourceColumn: Region

	column ResourceGroup
		dataType: string
		lineageTag: 45c7cad8-5942-4d30-b0de-8bc4a0f2850e
		summarizeBy: none
		sourceColumn: ResourceGroup

	column SubscriptionId
		dataType: string
		lineageTag: a97e4c21-4a4a-4efa-993a-15be315a5652
		summarizeBy: none
		sourceColumn: SubscriptionId

	column Endpoint
		dataType: string
		isHidden
		lineageTag: 59c5468f-608a-4711-9b20-ea348c1dde79
		summarizeBy: none
		sourceColumn: Endpoint

	column Sku
		dataType: string
		lineageTag: 0a30834b-7488-42ac-84e2-a61a966fa73a
		summarizeBy: none
		sourceColumn: Sku

	column PublicAccess
		dataType: string
		lineageTag: 109b4483-403d-454a-8dd4-137b1cb4a6cd
		summarizeBy: none
		sourceColumn: PublicAccess

	column LocalAuthOff
		dataType: boolean
		lineageTag: 1809ce5a-927c-417f-807a-716768515cec
		summarizeBy: none
		sourceColumn: LocalAuthOff

	column CreatedAt
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: 7516ed4c-d02e-442b-81d4-7c9d8934b629
		summarizeBy: none
		sourceColumn: CreatedAt

	partition AzureAIResource = m
		mode: import
		source =
				let
				    Raw = FnArg("resources | where type startswith 'microsoft.cognitiveservices' or type startswith 'microsoft.machinelearningservices' | where type !endswith 'deployments' | extend p = properties, resKind = tostring(kind) | extend isProject = (type endswith 'accounts/projects') or (resKind == 'Project') | project ResourceId = tostring(id), ResourceName = tostring(split(name, '/')[-1]), ParentAccount = iff(name has '/', tostring(split(name, '/')[0]), ''), ResourceType = tostring(type), Kind = resKind, Category = case(isProject, 'Foundry project', resKind == 'AIServices', 'AI Foundry account', resKind == 'Hub', 'Foundry hub', resKind == 'OpenAI', 'Azure OpenAI', resKind), IsAgentHost = isProject, Region = tostring(location), ResourceGroup = tostring(resourceGroup), SubscriptionId = tostring(subscriptionId), Endpoint = tostring(p.endpoint), Sku = tostring(sku.name), PublicAccess = tostring(p.publicNetworkAccess), LocalAuthOff = tobool(p.disableLocalAuth), CreatedAt = tostring(p.createdAtDate) | order by ResourceId asc"),
				    Kept = FnRecordsToTable(Raw, {"ResourceId", "ResourceName", "ParentAccount", "ResourceType", "Kind", "Category", "IsAgentHost", "Region", "ResourceGroup", "SubscriptionId", "Endpoint", "Sku", "PublicAccess", "LocalAuthOff", "CreatedAt"}),
				    Converted = Table.TransformColumns(Kept, {{"IsAgentHost", FnToBool, type logical}, {"LocalAuthOff", FnToBool, type logical}, {"CreatedAt", FnToDateTime, type datetime}}),
				    Final = Table.TransformColumnTypes(Converted, {{"ResourceId", type text}, {"ResourceName", type text}, {"ParentAccount", type text}, {"ResourceType", type text}, {"Kind", type text}, {"Category", type text}, {"Region", type text}, {"ResourceGroup", type text}, {"SubscriptionId", type text}, {"Endpoint", type text}, {"Sku", type text}, {"PublicAccess", type text}})
				in
				    Final

