/// Every distinct AppIdentity seen in the Purview audit log, classified by surface type and joined to the agent inventory where possible.
table CopilotSurface
	lineageTag: 1f7ccbdb-d298-48f1-aaf7-0c6d51d60888

	column SurfaceKey
		dataType: string
		isHidden
		lineageTag: 3ada1a8e-151b-40d2-8855-22e8534e199a
		summarizeBy: none
		sourceColumn: SurfaceKey

	/// Raw AppIdentity value from the audit record.
	column AppIdentity
		dataType: string
		lineageTag: 235dbb1e-9d81-42f2-b42f-596ac06c1037
		summarizeBy: none
		sourceColumn: AppIdentity

	/// Friendly name - the agent's display name where the surface resolved to an inventory agent.
	column SurfaceName
		dataType: string
		lineageTag: a416fd83-2dd9-4389-9828-0e3307c1672f
		summarizeBy: none
		sourceColumn: SurfaceName

	/// Agent Builder agent / Copilot Studio agent / Custom engine agent / M365 Copilot (base) / Microsoft 1P agent / Fabric copilot.
	column SurfaceType
		dataType: string
		lineageTag: 6148a7b9-58e1-4d1f-b75e-4ac8c4eb33bd
		summarizeBy: none
		sourceColumn: SurfaceType

	column Platform
		dataType: string
		lineageTag: 74c20b0b-372e-4d6d-8b72-58c1b8399938
		summarizeBy: none
		sourceColumn: Platform

	/// TRUE when the surface is a specific agent rather than a base Copilot experience.
	column IsAgent
		dataType: string
		lineageTag: b595a822-89c4-4932-8770-d43649132493
		summarizeBy: none
		sourceColumn: IsAgent

		annotation SummarizationSetBy = Automatic

	column AgentKey
		dataType: string
		isHidden
		lineageTag: c576fbfa-1b45-4fb3-bfe4-2f55c30155e0
		summarizeBy: none
		sourceColumn: AgentKey

	column AgentName
		dataType: string
		lineageTag: 8ab37561-2c2b-40f7-b3ce-0a7adbc89842
		summarizeBy: none
		sourceColumn: AgentName

	/// Which key joined the audit surface to the inventory: TitleId or SchemaName.
	column MatchOn
		dataType: string
		lineageTag: 743c9d3d-54ca-4e3d-8ff0-34447d4092ce
		summarizeBy: none
		sourceColumn: MatchOn

	/// TRUE when the surface was found in the agent inventory.
	column IsMatched
		dataType: boolean
		lineageTag: 9846e6d1-2949-44f8-8f07-6813ab8b9c88
		summarizeBy: none
		sourceColumn: IsMatched

	partition CopilotSurface = m
		mode: import
		source =
				let
				    Src = SrcSurfaceKey,
				    Ren = Table.RenameColumns(Src, {{"poc_appidentity", "SurfaceKey"}}),
				    Norm = Table.TransformColumns(Ren, {{"SurfaceKey", each if _ = null then "" else _, type text}}),
				    Keys = FnDistinctKey(Norm, "SurfaceKey"),
				    Classified = Table.AddColumn(Keys, "s", each FnSurface([SurfaceKey])),
				    Exp = Table.ExpandRecordColumn(Classified, "s", {"SurfaceType", "Platform", "MatchKey", "MatchOn", "DisplayName", "IsAgent"}),
				    Indexed = Table.AddColumn(Exp, "MatchIndex", each
				        if [IsAgent] and [MatchKey] <> "" then [MatchOn] & "|" & Text.Lower([MatchKey]) else null, type text),
				    Joined = Table.NestedJoin(Indexed, {"MatchIndex"}, FnAgentLookup(), {"MatchIndex"}, "agent", JoinKind.LeftOuter),
				    Agented = Table.ExpandTableColumn(Joined, "agent", {"AgentKey", "AgentName"}, {"AgentKey", "AgentName"}),
				    Filled = Table.TransformColumns(Agented, {
				        {"AgentKey", each if _ = null then "" else _, type text},
				        {"AgentName", each if _ = null then "" else _, type text}}),
				    WithId = Table.AddColumn(Filled, "AppIdentity", each [SurfaceKey], type text),
				    // Where the surface resolved to an inventory agent its display name wins, matching
				    // what Collect-CopilotAudit.ps1 wrote into DimCopilotSurface.csv.
				    WithName = Table.AddColumn(WithId, "SurfaceName", each if [AgentName] <> "" then [AgentName] else [DisplayName], type text),
				    WithMatched = Table.AddColumn(WithName, "IsMatched", each [AgentKey] <> "", type logical),
				    Kept = Table.SelectColumns(WithMatched, {"SurfaceKey", "AppIdentity", "SurfaceName", "SurfaceType", "Platform", "IsAgent", "AgentKey", "AgentName", "MatchOn", "IsMatched"}, MissingField.UseNull),
				    Typed = Table.TransformColumnTypes(Kept, {
				        {"SurfaceKey", type text}, {"AppIdentity", type text}, {"SurfaceName", type text}, {"SurfaceType", type text},
				        {"Platform", type text}, {"AgentKey", type text}, {"AgentName", type text}, {"MatchOn", type text}})
				in
				    Typed

