/// Contiguous date table generated in M from the DateStart parameter through the end of next month.
table Date
	lineageTag: b920fa27-b96f-466f-9501-bff218122208
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: yyyy-mm-dd
		lineageTag: c29dec95-6e4e-4696-904d-862a8d232425
		summarizeBy: none
		sourceColumn: Date

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 6866ae8d-700d-41f4-8a4a-ce98de5da1b8
		summarizeBy: sum
		sourceColumn: Year

	column Quarter
		dataType: string
		lineageTag: e7b94734-a7e4-47a4-ae11-6a80e046df1d
		summarizeBy: none
		sourceColumn: Quarter

	column MonthNo
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f0f566c7-3ecd-4723-a1d9-66d7a8691017
		summarizeBy: sum
		sourceColumn: MonthNo

	column MonthName
		dataType: string
		lineageTag: 0b6afc6b-9336-4845-bc86-2734f895f08e
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: MonthNo

	column YearMonth
		dataType: string
		lineageTag: b00c1417-1891-43a4-9cea-bbdee0c99f00
		summarizeBy: none
		sourceColumn: YearMonth

	column DayOfWeek
		dataType: string
		lineageTag: 2192376e-7c52-4443-b609-4f571fdce24f
		summarizeBy: none
		sourceColumn: DayOfWeek

	column IsWeekend
		dataType: boolean
		lineageTag: e1d440d8-df63-4120-9706-f08b32d332f2
		summarizeBy: none
		sourceColumn: IsWeekend

	partition Date = m
		mode: import
		source =
				let
				    Start = Date.From(DateStart),
				    Finish = Date.EndOfMonth(Date.AddMonths(Date.From(DateTimeZone.FixedUtcNow()), 1)),
				    Dates = List.Dates(Start, Duration.Days(Finish - Start) + 1, #duration(1, 0, 0, 0)),
				    T = Table.FromList(Dates, Splitter.SplitByNothing(), {"Date"}),
				    D = Table.TransformColumnTypes(T, {{"Date", type date}}),
				    Y = Table.AddColumn(D, "Year", each Date.Year([Date]), Int64.Type),
				    Q = Table.AddColumn(Y, "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date])), type text),
				    MN = Table.AddColumn(Q, "MonthNo", each Date.Month([Date]), Int64.Type),
				    MNm = Table.AddColumn(MN, "MonthName", each Date.MonthName([Date], "en-GB"), type text),
				    YM = Table.AddColumn(MNm, "YearMonth", each Text.From(Date.Year([Date])) & "-" & Text.PadStart(Text.From(Date.Month([Date])), 2, "0"), type text),
				    DW = Table.AddColumn(YM, "DayOfWeek", each Date.DayOfWeekName([Date], "en-GB"), type text),
				    WE = Table.AddColumn(DW, "IsWeekend", each Date.DayOfWeek([Date], Day.Monday) >= 5, type logical),
				    Kept = Table.SelectColumns(WE, {"Date", "Year", "Quarter", "MonthNo", "MonthName", "YearMonth", "DayOfWeek", "IsWeekend"}, MissingField.UseNull)
				in
				    Kept

