/// Power Platform environments - the security and data boundary each agent lives in.
table Environment
	lineageTag: 81cbcd6c-8432-48e3-be15-93e63a96d4ab

	column EnvironmentId
		dataType: string
		isHidden
		lineageTag: 40f995d5-47a7-482a-85d5-9b09e098cabd
		summarizeBy: none
		sourceColumn: EnvironmentId

	column EnvironmentName
		dataType: string
		lineageTag: 6372b854-dd7a-466b-9d75-aaf41e44c29d
		summarizeBy: none
		sourceColumn: EnvironmentName

	column Region
		dataType: string
		lineageTag: c512bee8-0b37-45ff-9681-c1f8741bb93c
		summarizeBy: none
		sourceColumn: Region

	column EnvironmentType
		dataType: string
		lineageTag: 17949366-8d29-49d1-a612-188c5b78a412
		summarizeBy: none
		sourceColumn: EnvironmentType

	column IsManaged
		dataType: boolean
		lineageTag: 402fbae6-3466-407a-aa6b-360e14cd081f
		summarizeBy: none
		sourceColumn: IsManaged

	column EnvironmentGroupId
		dataType: string
		isHidden
		lineageTag: bb57ab2d-e160-4ab8-b41d-0b1500365479
		summarizeBy: none
		sourceColumn: EnvironmentGroupId

	column CreatedAt
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: 93c3a320-86d5-4c9a-9db3-ca76809566b4
		summarizeBy: none
		sourceColumn: CreatedAt

	column LastModifiedAt
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: 09d1b2d7-48bd-4ba6-904a-d70fbc79b37c
		summarizeBy: none
		sourceColumn: LastModifiedAt

	column CreatedBy
		dataType: string
		isHidden
		lineageTag: 5aeb5aa3-1f57-4685-8393-7676ead5fe8c
		summarizeBy: none
		sourceColumn: CreatedBy

	partition Environment = m
		mode: import
		source =
				let
				    Raw = FnArg("PowerPlatformResources | where type =~ 'microsoft.powerplatform/environments' | extend p = properties | project EnvironmentId = tostring(name), EnvironmentName = tostring(p.displayName), Region = tostring(location), EnvironmentType = tostring(p.environmentType), IsManaged = tobool(p.isManaged), EnvironmentGroupId = tostring(p.environmentGroupId), CreatedAt = tostring(p.createdAt), LastModifiedAt = tostring(p.lastModifiedAt), CreatedBy = tostring(p.createdBy) | order by EnvironmentId asc"),
				    Kept = FnRecordsToTable(Raw, {"EnvironmentId", "EnvironmentName", "Region", "EnvironmentType", "IsManaged", "EnvironmentGroupId", "CreatedAt", "LastModifiedAt", "CreatedBy"}),
				    Converted = Table.TransformColumns(Kept, {{"IsManaged", FnToBool, type logical}, {"CreatedAt", FnToDateTime, type datetime}, {"LastModifiedAt", FnToDateTime, type datetime}}),
				    Final = Table.TransformColumnTypes(Converted, {{"EnvironmentId", type text}, {"EnvironmentName", type text}, {"Region", type text}, {"EnvironmentType", type text}, {"EnvironmentGroupId", type text}, {"CreatedBy", type text}})
				in
				    Final

