/// One row per Copilot turn from the Purview unified audit log. This is the only per-agent usage signal available for M365 Copilot Agent Builder agents.
table Interaction
	lineageTag: 6d2ad7ab-6b4e-4709-9466-c8274b77adb4

	column Date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 7fc29381-faf9-466a-8858-341da2ddbaf1
		summarizeBy: none
		sourceColumn: Date

		annotation UnderlyingDateTimeDataType = Date

	column CreationTime
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: 5b43b680-905b-42a3-bd13-b00babaee1d9
		summarizeBy: none
		sourceColumn: CreationTime

	/// AppIdentity from the audit record - the join key to CopilotSurface.
	column SurfaceKey
		dataType: string
		isHidden
		lineageTag: 7e8e8c73-f79a-431a-967a-c5712cd49e42
		summarizeBy: none
		sourceColumn: SurfaceKey

	/// Resolved inventory agent, blank when the surface is not an agent (base M365 Copilot, Microsoft first-party agents).
	column AgentKey
		dataType: string
		isHidden
		lineageTag: 5cc19d6c-1628-4510-8af4-d9066c9911f9
		summarizeBy: none
		sourceColumn: AgentKey

	/// The user who made the request.
	column UserPrincipalName
		dataType: string
		lineageTag: 54cf9d29-30eb-4c66-a9fb-075082d1710c
		summarizeBy: none
		sourceColumn: UserPrincipalName

	/// Client the interaction came from: Teams, Office, m365copilot, SharePoint, Copilot Studio, MCP, Autonomous...
	column AppHost
		dataType: string
		lineageTag: a82a0cbc-a11e-4126-be1d-66203f977627
		summarizeBy: none
		sourceColumn: AppHost

	column Operation
		dataType: string
		lineageTag: df519f85-5220-4fc6-bae2-68132bf3ab7b
		summarizeBy: none
		sourceColumn: Operation

	/// Conversation identifier - use to count sessions rather than turns.
	column ThreadId
		dataType: string
		isHidden
		lineageTag: 8b3c9469-2621-4095-a79f-49c89950bad8
		summarizeBy: none
		sourceColumn: ThreadId

	column MessageCount
		dataType: int64
		formatString: #,0
		lineageTag: 7e883c5e-01c1-489a-b0cf-1f405675bc25
		summarizeBy: sum
		sourceColumn: MessageCount

	/// How many files, sites, connectors or MCP tools the turn touched.
	column ResourceCount
		dataType: int64
		formatString: #,0
		lineageTag: 62ffaf35-79e9-4bb7-81e0-36d1e0d5851d
		summarizeBy: sum
		sourceColumn: ResourceCount

	/// Names of the resources the turn accessed, as reported by CopilotEventData.AccessedResources.
	column Resources
		dataType: string
		lineageTag: 090db451-0a45-4555-bd8f-c45af58ed5e6
		summarizeBy: none
		sourceColumn: Resources

	partition Interaction = m
		mode: import
		source =
				let
				    Src = SrcInteraction,
				    Ren = Table.RenameColumns(Src, {
				        {"poc_creationtime", "CreationTime"}, {"poc_appidentity", "SurfaceKey"}, {"poc_userid", "UserPrincipalName"},
				        {"poc_apphost", "AppHost"}, {"poc_operation", "Operation"}, {"poc_threadid", "ThreadId"},
				        {"poc_resourcecount", "ResourceCount"}, {"poc_resources", "Resources"}}),
				    // A null AppIdentity is a real surface (base M365 Copilot), so it has to carry the
				    // same empty-string key on both sides of the CopilotSurface relationship.
				    Keys = Table.TransformColumns(Ren, {{"SurfaceKey", each if _ = null then "" else _, type text}}),
				    Time = Table.TransformColumns(Keys, {{"CreationTime", each FnToDateTime(_), type datetime}}),
				    Dated = Table.AddColumn(Time, "Date", each if [CreationTime] = null then null else DateTime.Date([CreationTime]), type date),
				    Indexed = Table.AddColumn(Dated, "MatchIndex", each
				        let s = FnSurface([SurfaceKey]) in
				        if s[IsAgent] and s[MatchKey] <> "" then s[MatchOn] & "|" & Text.Lower(s[MatchKey]) else null, type text),
				    Joined = Table.NestedJoin(Indexed, {"MatchIndex"}, FnAgentLookup(), {"MatchIndex"}, "agent", JoinKind.LeftOuter),
				    Agented = Table.ExpandTableColumn(Joined, "agent", {"AgentKey"}, {"AgentKey"}),
				    Filled = Table.TransformColumns(Agented, {{"AgentKey", each if _ = null then "" else _, type text}}),
				    // CopilotEventData.MessageIds is always empty in the audit feed, so this stays zero
				    // and is retained only so the column contract matches the CSV branch.
				    Msgs = Table.AddColumn(Filled, "MessageCount", each 0, Int64.Type),
				    Kept = Table.SelectColumns(Msgs, {"Date", "CreationTime", "SurfaceKey", "AgentKey", "UserPrincipalName", "AppHost", "Operation", "ThreadId", "MessageCount", "ResourceCount", "Resources"}, MissingField.UseNull),
				    Typed = Table.TransformColumnTypes(Kept, {
				        {"SurfaceKey", type text}, {"AgentKey", type text}, {"UserPrincipalName", type text}, {"AppHost", type text},
				        {"Operation", type text}, {"ThreadId", type text}, {"Resources", type text}, {"ResourceCount", Int64.Type}})
				in
				    Typed

