/// Every individual governance risk factor that fired for an agent, with the points it contributed. Use this to explain a risk score.
table RiskDetail
	lineageTag: fb2fbff9-2144-442a-887e-5a0675659c7d

	column AgentKey
		dataType: string
		isHidden
		lineageTag: 7e7caf4a-81ba-48b6-a27f-79976921b343
		summarizeBy: none
		sourceColumn: AgentKey

	column AgentName
		dataType: string
		lineageTag: 325a133c-f916-411e-83c3-acda583cc474
		summarizeBy: none
		sourceColumn: AgentName

	column EnvironmentName
		dataType: string
		lineageTag: 9f0186e3-0323-4ae0-89ca-f174c5e2497f
		summarizeBy: none
		sourceColumn: EnvironmentName

	column Platform
		dataType: string
		lineageTag: b4d45474-3844-47b9-81d0-ee8963d82679
		summarizeBy: none
		sourceColumn: Platform

	/// The individual governance condition that fired.
	column RiskFactor
		dataType: string
		lineageTag: a23484a4-ddc3-4acd-899b-f5c9674bbd90
		summarizeBy: none
		sourceColumn: RiskFactor

	/// Points this factor contributed to the agent's total risk score.
	column Points
		dataType: int64
		formatString: #,0
		lineageTag: 7e573445-7b3c-4a0b-966e-e912dca374c6
		summarizeBy: sum
		sourceColumn: Points

	column RiskScore
		dataType: int64
		formatString: #,0
		lineageTag: de5eddf4-a069-4135-9fa3-5f57b8129bae
		summarizeBy: sum
		sourceColumn: RiskScore

	column RiskBand
		dataType: string
		lineageTag: ec5287cb-e832-4d64-8308-e4759fe62c7d
		summarizeBy: none
		sourceColumn: RiskBand

	partition RiskDetail = m
		mode: import
		source =
				let
				    Src = Table.SelectColumns(Agent, {"AgentKey", "AgentName", "EnvironmentName", "Platform", "Authentication",
				                                      "IsQuarantined", "SharedTenantWide", "WebSearchEnabled", "ConnectorCount",
				                                      "ConnectedAgentCount", "LastUsed"}, MissingField.UseNull),
				    // Mirrors Collect-AgentInventory.ps1 lines 433-440. Keep the two in step.
				    Factors = Table.AddColumn(Src, "f", each
				        let
				            // Matches PowerShell's -in semantics exactly: Azure Resource Graph omits
				            // null-valued fields, and neither -in nor List.Contains matches a null,
				            // so an absent authentication property deliberately does not fire.
				            noAuth  = List.Contains({"None", "No authentication", ""}, [Authentication]),
				            quar    = FnToLogical([IsQuarantined]) = true,
				            tenant  = FnToLogical([SharedTenantWide]) = true,
				            unused  = [LastUsed] = null,
				            web     = FnToLogical([WebSearchEnabled]) = true,
				            conn    = [ConnectorCount] <> null and [ConnectorCount] > 0,
				            linked  = [ConnectedAgentCount] <> null and [ConnectedAgentCount] > 0
				        in
				            List.Combine({
				                if noAuth then {[RiskFactor = "No authentication configured", Points = 3]} else {},
				                if quar   then {[RiskFactor = "Agent is quarantined", Points = 3]} else {},
				                if tenant then {[RiskFactor = "Shared with the entire tenant", Points = 2]} else {},
				                if tenant and unused then {[RiskFactor = "Shared tenant-wide and never used", Points = 1]} else {},
				                if web    then {[RiskFactor = "Web search enabled on knowledge", Points = 1]} else {},
				                if conn   then {[RiskFactor = "Uses one or more connectors", Points = 1]} else {},
				                if linked then {[RiskFactor = "Connected to other agents", Points = 1]} else {}})),
				    Scored = Table.AddColumn(Factors, "RiskScore", each
				        let s = List.Sum(List.Transform([f], each _[Points])) in if s = null then 0 else s, Int64.Type),
				    Banded = Table.AddColumn(Scored, "RiskBand", each if [RiskScore] >= 5 then "High" else if [RiskScore] >= 3 then "Medium" else "Low", type text),
				    Fired  = Table.SelectRows(Banded, each List.Count([f]) > 0),
				    Expand = Table.ExpandListColumn(Fired, "f"),
				    Flat   = Table.ExpandRecordColumn(Expand, "f", {"RiskFactor", "Points"}, {"RiskFactor", "Points"}),
				    Kept   = Table.SelectColumns(Flat, {"AgentKey", "AgentName", "EnvironmentName", "Platform", "RiskFactor", "Points", "RiskScore", "RiskBand"}, MissingField.UseNull),
				    Typed  = Table.TransformColumnTypes(Kept, {{"AgentKey", type text}, {"AgentName", type text}, {"EnvironmentName", type text},
				                                              {"Platform", type text}, {"RiskFactor", type text}, {"Points", Int64.Type}})
				in
				    Typed

