/// Entra ID principals that created or own agents. Live mode resolves them from Dataverse systemusers; CSV mode from Microsoft Graph directoryObjects/getByIds.
table User
	lineageTag: b3c6b71d-1bb1-429d-bdbc-296bc01713fe

	column UserKey
		dataType: string
		isHidden
		lineageTag: 1b744960-9e20-467c-90f9-c3ff012381d3
		summarizeBy: none
		sourceColumn: UserKey

	column DisplayName
		dataType: string
		lineageTag: c3371ea7-68dd-4f06-be61-7d164817a486
		summarizeBy: none
		sourceColumn: DisplayName

	column UserPrincipalName
		dataType: string
		lineageTag: d940349f-f96b-4cf2-9f8a-94c7c2708c25
		summarizeBy: none
		sourceColumn: UserPrincipalName

	/// user / servicePrincipal / group.
	column PrincipalType
		dataType: string
		lineageTag: 440bb6b6-c096-4704-a0fe-6f9b5fbd9a81
		summarizeBy: none
		sourceColumn: PrincipalType

	partition User = m
		mode: import
		source =
				let
				    Src = FnDataverse("systemusers", {"azureactivedirectoryobjectid", "fullname", "internalemailaddress", "applicationid"}),
				    // OData.Feed returns Edm.Guid as a Guid value, not text. UserKey joins to
				    // Agent[OwnerId], which is text, so both guid columns are coerced explicitly.
				    Typed0 = Table.AddColumn(Src, "PrincipalType", each if [applicationid] = null then "user" else "application", type text),
				    AsText = Table.TransformColumns(Typed0, {{"azureactivedirectoryobjectid", each if _ = null then null else Text.Lower(Text.From(_)), type text}}),
				    Real = Table.SelectRows(AsText, each [azureactivedirectoryobjectid] <> null and [azureactivedirectoryobjectid] <> ""),
				    Ren = Table.RenameColumns(Real, {{"azureactivedirectoryobjectid", "UserKey"}, {"fullname", "DisplayName"}, {"internalemailaddress", "UserPrincipalName"}}),
				    Uniq = FnDistinctKey(Ren, "UserKey"),
				    Kept = Table.SelectColumns(Uniq, {"UserKey", "DisplayName", "UserPrincipalName", "PrincipalType"}, MissingField.UseNull),
				    Typed = Table.TransformColumnTypes(Kept, {{"UserKey", type text}, {"DisplayName", type text}, {"UserPrincipalName", type text}})
				in
				    Typed

