/// One row per agent-to-connector binding, including MCP server tools.
table AgentConnector
	lineageTag: 60aa03eb-bace-408e-84c0-3241c2339f02

	column AgentKey
		dataType: string
		isHidden
		lineageTag: f44cea65-57ce-4111-badc-4c9b7a20d8ac
		summarizeBy: none
		sourceColumn: AgentKey

	column ConnectorId
		dataType: string
		lineageTag: 345de2f2-a473-4c2c-9e89-c7ae13e9503a
		summarizeBy: none
		sourceColumn: ConnectorId

	column OperationCount
		dataType: int64
		formatString: #,0
		lineageTag: feed8de5-6717-47a5-bac6-465eef3dd5cc
		summarizeBy: sum
		sourceColumn: OperationCount

	/// TRUE when the connector operation list advertises an MCP server tool.
	column IsMcpServer
		dataType: boolean
		lineageTag: 08882260-2318-492f-8572-51ef82e240c4
		summarizeBy: none
		sourceColumn: IsMcpServer

	partition AgentConnector = m
		mode: import
		source =
				let
				    Source = if SourceMode = "Live" then (
				        let
				            Raw = FnArg("PowerPlatformResources | where type =~ 'microsoft.copilotstudio/agents' | extend p = properties | mv-expand conn = p.powerPlatformConnectors | where isnotnull(conn) | project AgentKey = strcat(tostring(p.environmentId), '|', tostring(name)), ConnectorId = tostring(conn.connectorId), OperationCount = coalesce(array_length(conn.operations), 0), IsMcpServer = tostring(conn.operations) contains '""type"":""MCP""'"),
				            Kept = FnRecordsToTable(Raw, {"AgentKey", "ConnectorId", "OperationCount", "IsMcpServer"}),
				            Converted = Table.TransformColumns(Kept, {{"OperationCount", FnToInt, Int64.Type}, {"IsMcpServer", FnToBool, type logical}}),
				            Final = Table.TransformColumnTypes(Converted, {{"AgentKey", type text}, {"ConnectorId", type text}})
				        in
				            Final
				    ) else (
				        let
				            Source = Csv.Document(File.Contents(DataFolder & "\FactAgentConnector.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				            Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				            Kept = Table.SelectColumns(Headers, {"AgentKey", "ConnectorId", "OperationCount", "IsMcpServer"}, MissingField.UseNull),
				            Converted = Table.TransformColumns(Kept, {{"OperationCount", FnToInt, Int64.Type}, {"IsMcpServer", FnToBool, type logical}}),
				            Typed = Table.TransformColumnTypes(Converted, {{"AgentKey", type text}, {"ConnectorId", type text}})
				        in
				            Typed
				    )
				in
				    Source

