/// Every distinct AppIdentity seen in the Purview audit log, classified by surface type and joined to the agent inventory where possible.
table CopilotSurface
	lineageTag: a11967a9-224f-4492-aeb8-f60c27d7df91

	column SurfaceKey
		dataType: string
		isHidden
		lineageTag: 44a365de-130d-4d9c-a9a6-81fb3e2c3360
		summarizeBy: none
		sourceColumn: SurfaceKey

	/// Raw AppIdentity value from the audit record.
	column AppIdentity
		dataType: string
		lineageTag: b9f6f00f-7a30-457e-b53e-d0cde219424d
		summarizeBy: none
		sourceColumn: AppIdentity

	/// Friendly name - the agent's display name where the surface resolved to an inventory agent.
	column SurfaceName
		dataType: string
		lineageTag: 24ea0c0c-6876-455b-8a63-9a49a09f74c1
		summarizeBy: none
		sourceColumn: SurfaceName

	/// Agent Builder agent / Copilot Studio agent / Custom engine agent / M365 Copilot (base) / Microsoft 1P agent / Fabric copilot.
	column SurfaceType
		dataType: string
		lineageTag: e959452f-d258-4b39-b90e-d623c96230e1
		summarizeBy: none
		sourceColumn: SurfaceType

	column Platform
		dataType: string
		lineageTag: ba833c25-873c-4641-9821-a834d4c14d95
		summarizeBy: none
		sourceColumn: Platform

	/// TRUE when the surface is a specific agent rather than a base Copilot experience.
	column IsAgent
		dataType: boolean
		lineageTag: ed76b0e7-26d8-49fe-b1b1-ee19349e9213
		summarizeBy: none
		sourceColumn: IsAgent

	column AgentKey
		dataType: string
		isHidden
		lineageTag: 4001df91-0657-42ca-8be1-b53c58b67853
		summarizeBy: none
		sourceColumn: AgentKey

	column AgentName
		dataType: string
		lineageTag: 8deed45b-cba2-4e9a-922c-fe360959dfcb
		summarizeBy: none
		sourceColumn: AgentName

	/// Which key joined the audit surface to the inventory: TitleId or SchemaName.
	column MatchOn
		dataType: string
		lineageTag: 25ccf2f6-921c-4440-b4de-91eb61d77f5f
		summarizeBy: none
		sourceColumn: MatchOn

	/// TRUE when the surface was found in the agent inventory.
	column IsMatched
		dataType: boolean
		lineageTag: 679f960b-950f-4184-b85d-cd744b670551
		summarizeBy: none
		sourceColumn: IsMatched

	/// For a SharePoint agent, the site collection the .agent file lives in. Blank for every other surface.
	column SharePointSiteId
		dataType: string
		lineageTag: 2f7a4b90-6c31-4d58-ae12-9b03d7e6c845
		summarizeBy: none
		sourceColumn: SharePointSiteId

	/// For a SharePoint agent, the document library item id of the .agent file. Blank for every other surface.
	column SharePointItemId
		dataType: string
		lineageTag: 5e91c8d3-b7f0-4a26-8c94-3d15ba70e9f7
		summarizeBy: none
		sourceColumn: SharePointItemId

	column SharePointWebId
		dataType: string
		lineageTag: c14eb563-5857-4dbc-aa64-89528796b76f
		summarizeBy: none
		sourceColumn: SharePointWebId

	column SharePointListId
		dataType: string
		lineageTag: 15c925fb-6168-48b5-8248-b62aed895bea
		summarizeBy: none
		sourceColumn: SharePointListId

	/// ListItemUniqueId decoded from the opaque SharePoint drive-item id. This is the exact join key to SharePointAgent.
	column SharePointItemGuid
		dataType: string
		lineageTag: e457965a-cecb-4185-ad3b-236de16ce2ef
		summarizeBy: none
		sourceColumn: SharePointItemGuid

	column SharePointAgentKey
		dataType: string
		isHidden
		lineageTag: f5d60ca3-34cf-4744-8db4-904432837def
		summarizeBy: none
		sourceColumn: SharePointAgentKey

	column SharePointAgentName
		dataType: string
		lineageTag: 6d838cf5-f021-4cf7-acbb-a1a9ed2e0960
		summarizeBy: none
		sourceColumn: SharePointAgentName

	column SharePointSiteUrl
		dataType: string
		lineageTag: 0a2abf18-6a8c-48f6-93f7-730c1f3abeb9
		summarizeBy: none
		sourceColumn: SharePointSiteUrl

	column SharePointObjectUrl
		dataType: string
		lineageTag: b02b65ac-3534-4c95-aa70-5ea8e1989226
		summarizeBy: none
		sourceColumn: SharePointObjectUrl

	column SharePointIsDeleted
		dataType: boolean
		lineageTag: e4b4494f-3c1d-4f96-b614-45bbf63450ca
		summarizeBy: none
		sourceColumn: SharePointIsDeleted

	partition CopilotSurface = m
		mode: import
		source =
				let
				    Bin = try File.Contents(DataFolder & "\DimCopilotSurface.csv") otherwise null,
				    Source = if Bin = null then #table(type table [#"SurfaceKey" = text, #"AppIdentity" = text, #"SurfaceName" = text, #"SurfaceType" = text, #"Platform" = text, #"IsAgent" = logical, #"AgentKey" = text, #"AgentName" = text, #"MatchOn" = text, #"IsMatched" = logical, #"SharePointSiteId" = text, #"SharePointItemId" = text], {}) else Csv.Document(Bin, [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Headers = if Bin = null then Source else Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Base = Table.SelectColumns(Headers, {"SurfaceKey", "AppIdentity", "SurfaceName", "SurfaceType", "Platform", "IsAgent", "AgentKey", "AgentName", "MatchOn", "IsMatched"}, MissingField.UseNull),
				    Converted = Table.TransformColumns(Base, {{"IsAgent", FnToBool, type logical}, {"IsMatched", FnToBool, type logical}}),
				    WithSpo = Table.AddColumn(Converted, "spo", each FnSpo([SurfaceKey])),
				    SpoExp = Table.ExpandRecordColumn(WithSpo, "spo", {"SiteId", "WebId", "ListId", "ItemId", "ItemGuid"}, {"SharePointSiteId", "SharePointWebId", "SharePointListId", "SharePointItemId", "SharePointItemGuid"}),
				    SpoKeyed = Table.AddColumn(SpoExp, "SharePointAgentKey", each Text.Lower([SharePointItemGuid]), type text),
				    SpoJoined = Table.NestedJoin(SpoKeyed, {"SharePointAgentKey"}, FnSharePointAgentLookup(), {"AgentKey"}, "spAgent", JoinKind.LeftOuter),
				    SpoAgented = Table.ExpandTableColumn(SpoJoined, "spAgent", {"AgentKey", "AgentName", "SiteUrl", "ObjectUrl", "IsDeleted"}, {"MatchedSharePointAgentKey", "SharePointAgentName", "SharePointSiteUrl", "SharePointObjectUrl", "SharePointIsDeleted"}),
				    SpoFilled = Table.TransformColumns(SpoAgented, {
				        {"MatchedSharePointAgentKey", each if _ = null then "" else _, type text},
				        {"SharePointAgentName", each if _ = null then "" else _, type text},
				        {"SharePointSiteUrl", each if _ = null then "" else _, type text},
				        {"SharePointObjectUrl", each if _ = null then "" else _, type text}}),
				    Named = Table.AddColumn(SpoFilled, "ResolvedSurfaceName", each if [SharePointAgentName] <> "" then [SharePointAgentName] else [SurfaceName], type text),
				    Matched = Table.AddColumn(Named, "ResolvedIsMatched", each [IsMatched] or [MatchedSharePointAgentKey] <> "", type logical),
				    Removed = Table.RemoveColumns(Matched, {"SurfaceName", "IsMatched", "MatchedSharePointAgentKey"}),
				    Renamed = Table.RenameColumns(Removed, {{"ResolvedSurfaceName", "SurfaceName"}, {"ResolvedIsMatched", "IsMatched"}}),
				    Kept = Table.SelectColumns(Renamed, {"SurfaceKey", "AppIdentity", "SurfaceName", "SurfaceType", "Platform", "IsAgent", "AgentKey", "AgentName", "MatchOn", "IsMatched", "SharePointSiteId", "SharePointWebId", "SharePointListId", "SharePointItemId", "SharePointItemGuid", "SharePointAgentKey", "SharePointAgentName", "SharePointSiteUrl", "SharePointObjectUrl", "SharePointIsDeleted"}, MissingField.UseNull),
				    Typed = Table.TransformColumnTypes(Kept, {
				        {"SurfaceKey", type text}, {"AppIdentity", type text}, {"SurfaceName", type text}, {"SurfaceType", type text},
				        {"Platform", type text}, {"AgentKey", type text}, {"AgentName", type text}, {"MatchOn", type text},
				        {"SharePointSiteId", type text}, {"SharePointWebId", type text}, {"SharePointListId", type text},
				        {"SharePointItemId", type text}, {"SharePointItemGuid", type text}, {"SharePointAgentKey", type text},
				        {"SharePointAgentName", type text}, {"SharePointSiteUrl", type text}, {"SharePointObjectUrl", type text},
				        {"SharePointIsDeleted", type logical}})
				in
				    Typed
