/// Contiguous date table generated by the collector.
table Date
	lineageTag: c384c550-1680-4e75-bfc8-55e8932c52d2
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: yyyy-mm-dd
		lineageTag: ae3c01c6-c10d-484e-9b60-09745e7449ff
		summarizeBy: none
		sourceColumn: Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 222ddeb2-0b8a-4809-afb8-f5be53967767
		summarizeBy: sum
		sourceColumn: Year

	column Quarter
		dataType: string
		lineageTag: b69473ab-7e4a-49f2-abaa-3ec8ab7eb137
		summarizeBy: none
		sourceColumn: Quarter

	column MonthNo
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c46a864b-5850-4bbc-b2b8-d03179e24350
		summarizeBy: sum
		sourceColumn: MonthNo

	column MonthName
		dataType: string
		lineageTag: 794de9a4-9a7e-4f6c-bbf1-9e4872971fd3
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: MonthNo

	column YearMonth
		dataType: string
		lineageTag: d631f9d3-4d9b-4abf-9fab-253338b53a79
		summarizeBy: none
		sourceColumn: YearMonth

	column DayOfWeek
		dataType: string
		lineageTag: 955883f7-e7fb-4cc9-b77c-222dfab33e89
		summarizeBy: none
		sourceColumn: DayOfWeek

	column IsWeekend
		dataType: boolean
		lineageTag: b630eb8e-757b-4748-9db8-1324840ab422
		summarizeBy: none
		sourceColumn: IsWeekend

	partition Date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\DimDate.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Kept = Table.SelectColumns(Headers, {"Date", "Year", "Quarter", "MonthNo", "MonthName", "YearMonth", "DayOfWeek", "IsWeekend"}, MissingField.UseNull),
				    Converted = Table.TransformColumns(Kept, {{"Date", FnToDate, type date}, {"Year", FnToInt, Int64.Type}, {"MonthNo", FnToInt, Int64.Type}, {"IsWeekend", FnToBool, type logical}}),
				    Typed = Table.TransformColumnTypes(Converted, {{"Quarter", type text}, {"MonthName", type text}, {"YearMonth", type text}, {"DayOfWeek", type text}})
				in
				    Typed

