/// One row per Copilot turn from the Purview unified audit log. This is the only per-agent usage signal available for M365 Copilot Agent Builder agents.
table Interaction
	lineageTag: 9475c255-0ead-47b2-8afa-e34c9a7f50e2

	column Date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 7a791ba9-75e5-4c12-8d36-b80accc23394
		summarizeBy: none
		sourceColumn: Date

	column CreationTime
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: 5c1298d6-8ce7-4eef-84b7-fc37ae866914
		summarizeBy: none
		sourceColumn: CreationTime

	/// AppIdentity from the audit record - the join key to CopilotSurface.
	column SurfaceKey
		dataType: string
		isHidden
		lineageTag: 0ae64b3f-c871-474d-8678-8362bb429ecf
		summarizeBy: none
		sourceColumn: SurfaceKey

	/// Resolved inventory agent, blank when the surface is not an agent (base M365 Copilot, Microsoft first-party agents).
	column AgentKey
		dataType: string
		isHidden
		lineageTag: 68bfe140-6f9d-45dd-b8ad-78166243236d
		summarizeBy: none
		sourceColumn: AgentKey

	/// The user who made the request.
	column UserPrincipalName
		dataType: string
		lineageTag: 58ce70e3-59bd-4b37-9398-0e77a9061b82
		summarizeBy: none
		sourceColumn: UserPrincipalName

	/// Client the interaction came from: Teams, Office, m365copilot, SharePoint, Copilot Studio, MCP, Autonomous...
	column AppHost
		dataType: string
		lineageTag: 40af51f0-114d-44d3-896d-122034e73ece
		summarizeBy: none
		sourceColumn: AppHost

	column Operation
		dataType: string
		lineageTag: 8173f9e3-3651-4739-ac5a-1330067f7b60
		summarizeBy: none
		sourceColumn: Operation

	/// Conversation identifier - use to count sessions rather than turns.
	column ThreadId
		dataType: string
		isHidden
		lineageTag: ee826921-ec9d-4314-9a76-cdada344e28f
		summarizeBy: none
		sourceColumn: ThreadId

	column MessageCount
		dataType: int64
		formatString: #,0
		lineageTag: 799164c0-5f1f-477b-9abb-112806b785d2
		summarizeBy: sum
		sourceColumn: MessageCount

	/// How many files, sites, connectors or MCP tools the turn touched.
	column ResourceCount
		dataType: int64
		formatString: #,0
		lineageTag: f2cb6663-f96c-4759-9d70-4d5507cc24a4
		summarizeBy: sum
		sourceColumn: ResourceCount

	/// Names of the resources the turn accessed, as reported by CopilotEventData.AccessedResources.
	column Resources
		dataType: string
		lineageTag: 7541ad2b-0b65-4b9a-8303-967e2587c23a
		summarizeBy: none
		sourceColumn: Resources

	partition Interaction = m
		mode: import
		source =
				let
				    Bin = try File.Contents(DataFolder & "\FactCopilotInteraction.csv") otherwise null,
				    Source = if Bin = null then #table(type table [#"Date" = date, #"CreationTime" = datetime, #"SurfaceKey" = text, #"AgentKey" = text, #"UserPrincipalName" = text, #"AppHost" = text, #"Operation" = text, #"ThreadId" = text, #"MessageCount" = Int64.Type, #"ResourceCount" = Int64.Type, #"Resources" = text], {}) else Csv.Document(Bin, [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Headers = if Bin = null then Source else Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Kept = Table.SelectColumns(Headers, {"Date", "CreationTime", "SurfaceKey", "AgentKey", "UserPrincipalName", "AppHost", "Operation", "ThreadId", "MessageCount", "ResourceCount", "Resources"}, MissingField.UseNull),
				    Converted = Table.TransformColumns(Kept, {{"Date", FnToDate, type date}, {"CreationTime", FnToDateTime, type datetime}, {"MessageCount", FnToInt, Int64.Type}, {"ResourceCount", FnToInt, Int64.Type}}),
				    Typed = Table.TransformColumnTypes(Converted, {{"SurfaceKey", type text}, {"AgentKey", type text}, {"UserPrincipalName", type text}, {"AppHost", type text}, {"Operation", type text}, {"ThreadId", type text}, {"Resources", type text}})
				in
				    Typed

