/// Every Copilot Studio and Microsoft 365 Copilot Agent Builder agent in the tenant, sourced from the Power Platform inventory exposed through Azure Resource Graph.
table Agent
	lineageTag: ff515e8d-e8be-468b-832f-25e8165ab140

	/// Unique agent identifier: environment id + agent id. Microsoft's pre-installed first-party agents reuse the same agent id in every environment, so the environment must be part of the key.
	column AgentKey
		dataType: string
		isHidden
		lineageTag: f54e931c-e87f-4941-a387-d5a87d100ad4
		summarizeBy: none
		sourceColumn: AgentKey

	/// Raw agent (bot) identifier from the Power Platform inventory. Not unique across environments for first-party agents.
	column AgentId
		dataType: string
		isHidden
		lineageTag: 2053d327-a843-49da-911b-cbcba8bde1c6
		summarizeBy: none
		sourceColumn: AgentId

	/// Display name of the agent.
	column AgentName
		dataType: string
		lineageTag: bdf31b23-8227-423f-8c2b-9f4e60536d83
		summarizeBy: none
		sourceColumn: AgentName

	/// Normalised authoring platform: Copilot Studio, M365 Copilot Agent Builder or Azure AI Foundry.
	column Platform
		dataType: string
		lineageTag: 7a18606b-c592-4c54-9341-f350dd6fedee
		summarizeBy: none
		sourceColumn: Platform

	/// Raw createdIn value reported by the Power Platform inventory API.
	column AuthoringSurface
		dataType: string
		lineageTag: 652a5b5a-7421-4a0b-983f-862679a74436
		summarizeBy: none
		sourceColumn: AuthoringSurface

	column EnvironmentId
		dataType: string
		isHidden
		lineageTag: 5f89037e-89f0-4df7-ae64-31c80014c138
		summarizeBy: none
		sourceColumn: EnvironmentId

	column EnvironmentName
		dataType: string
		lineageTag: 2916240d-7ae3-44b6-ac6c-416fde895368
		summarizeBy: none
		sourceColumn: EnvironmentName

	column EnvironmentType
		dataType: string
		lineageTag: 8c5886f4-b73c-43ad-8f57-9c626b12bc06
		summarizeBy: none
		sourceColumn: EnvironmentType

	column Region
		dataType: string
		lineageTag: 4a2ed80b-cd6a-4d35-9698-9de05123b07e
		summarizeBy: none
		sourceColumn: Region

	column SchemaName
		dataType: string
		isHidden
		lineageTag: 214b8db2-234d-43f8-a1e4-4103d374bf4d
		summarizeBy: none
		sourceColumn: SchemaName

	/// Generative (AI orchestration) or Classic (topic driven).
	column Orchestration
		dataType: string
		lineageTag: 931c96b0-3ec5-4c3f-9215-4f9ba0b50abf
		summarizeBy: none
		sourceColumn: Orchestration

	/// Underlying LLM the agent is configured to use.
	column Model
		dataType: string
		lineageTag: 9c865de5-ec0f-4f5c-b228-bd07d2975989
		summarizeBy: none
		sourceColumn: Model

	/// Authentication mode. 'None' means anonymous end-user access.
	column Authentication
		dataType: string
		lineageTag: 60dc8007-e89f-4ad1-8000-0f8c3960cc36
		summarizeBy: none
		sourceColumn: Authentication

	column CreatedAt
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: 47b2b654-df1b-4fea-ae0f-71cb0a9906a9
		summarizeBy: none
		sourceColumn: CreatedAt

	column LastPublishedAt
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: 737b27e0-bb5d-4486-aa91-0bc278ded72b
		summarizeBy: none
		sourceColumn: LastPublishedAt

	/// Latest usage signal from Power Platform usage records.
	column LastUsed
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: 8307c30e-2b7c-44b9-bceb-4eeeba092ad9
		summarizeBy: none
		sourceColumn: LastUsed

	column IsPublished
		dataType: boolean
		lineageTag: 9ebdb9a4-84f5-4761-a9aa-fbdedbda3c51
		summarizeBy: none
		sourceColumn: IsPublished

	column IsQuarantined
		dataType: boolean
		lineageTag: e2be20e5-4c4a-4926-b735-e6066fbef98a
		summarizeBy: none
		sourceColumn: IsQuarantined

	column IsManaged
		dataType: boolean
		lineageTag: 194f8ce7-98f5-47de-a38a-5802e7624a51
		summarizeBy: none
		sourceColumn: IsManaged

	column IsGithubCopilotAgent
		dataType: boolean
		lineageTag: b52a9d69-5e6e-43b6-b827-c34c0921242e
		summarizeBy: none
		sourceColumn: IsGithubCopilotAgent

	column IsCLIAgent
		dataType: boolean
		lineageTag: 9419621b-ed9d-42ff-991c-e19b81bcd223
		summarizeBy: none
		sourceColumn: IsCLIAgent

	column WebSearchEnabled
		dataType: boolean
		lineageTag: 1c9ddb91-794e-4bc0-9d4c-fe391d69104f
		summarizeBy: none
		sourceColumn: WebSearchEnabled

	column Channels
		dataType: string
		lineageTag: 206cdfeb-78ef-4989-8fae-1aeb482a3f24
		summarizeBy: none
		sourceColumn: Channels

	column ChannelCount
		dataType: int64
		formatString: #,0
		lineageTag: c84dea92-420a-4034-a640-d8358020c89b
		summarizeBy: sum
		sourceColumn: ChannelCount

	column TopicCount
		dataType: int64
		formatString: #,0
		lineageTag: 365ef1d2-0fab-4c70-8f65-d7ce57a0c806
		summarizeBy: sum
		sourceColumn: TopicCount

	column ToolCount
		dataType: int64
		formatString: #,0
		lineageTag: a2112ea7-5810-4a34-8d72-55cc00fc0bcb
		summarizeBy: sum
		sourceColumn: ToolCount

	column KnowledgeCount
		dataType: int64
		formatString: #,0
		lineageTag: 8d6b1dd4-40bf-463d-a0ce-7b0f012ee732
		summarizeBy: sum
		sourceColumn: KnowledgeCount

	column ConnectedAgentCount
		dataType: int64
		formatString: #,0
		lineageTag: 72edbafc-5413-45cc-a0fa-2718e9dd0d8f
		summarizeBy: sum
		sourceColumn: ConnectedAgentCount

	column ConnectorCount
		dataType: int64
		formatString: #,0
		lineageTag: f22fedd7-f826-4a71-8157-72745c3b08ca
		summarizeBy: sum
		sourceColumn: ConnectorCount

	column ConnectorOpsCount
		dataType: int64
		formatString: #,0
		lineageTag: b394f7fc-40cd-45b5-83ae-c6ffa1ecaca9
		summarizeBy: sum
		sourceColumn: ConnectorOpsCount

	column FlowCount
		dataType: int64
		formatString: #,0
		lineageTag: 9670a709-b0c1-4c45-ad7b-23ddd48b74ee
		summarizeBy: sum
		sourceColumn: FlowCount

	column SharedUserCount
		dataType: int64
		formatString: #,0
		lineageTag: 2bd9c9d3-6340-4c4e-a5c0-cc5cf3594adc
		summarizeBy: sum
		sourceColumn: SharedUserCount

	column SharedGroupCount
		dataType: int64
		formatString: #,0
		lineageTag: 5ec9ffe9-513e-46fb-ac84-8daaab3489d0
		summarizeBy: sum
		sourceColumn: SharedGroupCount

	/// TRUE when the agent is shared with everyone in the tenant.
	column SharedTenantWide
		dataType: boolean
		lineageTag: 1b8d5bfb-37e8-4b0d-8180-bda08b39cfa1
		summarizeBy: none
		sourceColumn: SharedTenantWide

	column EditorUserCount
		dataType: int64
		formatString: #,0
		lineageTag: f28b9f79-8bd4-49e0-874f-53723aba6bf1
		summarizeBy: sum
		sourceColumn: EditorUserCount

	column OwnerId
		dataType: string
		isHidden
		lineageTag: a26fba81-2fa8-4e2d-9467-af408554b668
		summarizeBy: none
		sourceColumn: OwnerId

	column CreatedBy
		dataType: string
		isHidden
		lineageTag: a73f8ff1-6635-4ca9-9f4a-07d7ff6922f3
		summarizeBy: none
		sourceColumn: CreatedBy

	/// Display name of the agent's creator, resolved from Entra ID via Microsoft Graph directoryObjects/getByIds.
	column CreatedByName = IF ( 'Agent'[CreatedBy] = "00000000-0000-0000-0000-000000000000", "System / platform", LOOKUPVALUE ( 'User'[DisplayName], 'User'[UserKey], 'Agent'[CreatedBy] ) )
		dataType: string
		lineageTag: e0f9ed43-0d4b-4fd9-98e3-0cbc74789ff9
		summarizeBy: none

	/// Display name of the agent's current owner.
	column OwnerName = IF ( 'Agent'[OwnerId] = "00000000-0000-0000-0000-000000000000", "System / platform", RELATED ( 'User'[DisplayName] ) )
		dataType: string
		lineageTag: e58a41f4-f088-4893-81f8-e15e7bb9747a
		summarizeBy: none

	/// User principal name of the owner, where the identity resolved to a user.
	column OwnerUpn = RELATED ( 'User'[UserPrincipalName] )
		dataType: string
		lineageTag: 1609e37a-2e2d-4e90-bc3c-b85205b989c2
		summarizeBy: none

	column EntraAppId
		dataType: string
		isHidden
		lineageTag: 3da7223e-a14f-4622-9c98-dc2f8ef6cfac
		summarizeBy: none
		sourceColumn: EntraAppId

	column TitleId
		dataType: string
		isHidden
		lineageTag: baadcdb6-c2f8-4961-8154-1ce518bd4f38
		summarizeBy: none
		sourceColumn: TitleId

	column DaysSinceLastUse
		dataType: int64
		formatString: #,0
		lineageTag: e4715418-9164-43d7-aa87-d557bd9cec91
		summarizeBy: sum
		sourceColumn: DaysSinceLastUse

	column AgeDays
		dataType: int64
		formatString: #,0
		lineageTag: f23dfceb-5720-497f-9665-077245ef7529
		summarizeBy: sum
		sourceColumn: AgeDays

	column CreatedMonth
		dataType: string
		lineageTag: f615d379-bb93-4a59-9c3c-9e0cb3e14c37
		summarizeBy: none
		sourceColumn: CreatedMonth

	/// Active (7d) / Active (30d) / Idle (90d) / Dormant (90d+) / No usage signal.
	/// Activity according to Power Platform usage records alone. These cover only 9.7% of Copilot Studio agents and none of Agent Builder, so prefer ActivityStatus.
	column ActivityStatusUsageRecords
		dataType: string
		lineageTag: 281da3a7-34e7-4001-96c2-ca7f9ab79aef
		summarizeBy: none
		sourceColumn: ActivityStatus

	/// Heuristic governance risk score (0-11).
	column RiskScore
		dataType: int64
		formatString: #,0
		lineageTag: 2056e5a1-ce98-43ae-aa6e-5ccbb9e51c5d
		summarizeBy: sum
		sourceColumn: RiskScore

	/// Low (<3), Medium (3-4), High (5+).
	column RiskBand
		dataType: string
		lineageTag: 382c299c-1758-444d-b5b9-5d80672ea68a
		summarizeBy: none
		sourceColumn: RiskBand

	/// How many individual risk factors fired for this agent.
	column RiskFactorCount
		dataType: int64
		formatString: #,0
		lineageTag: a28a6845-a094-4658-b9bb-db069bafa493
		summarizeBy: sum
		sourceColumn: RiskFactorCount

	/// Human-readable list of every risk factor that contributed to the score, with its point value.
	column RiskReasons
		dataType: string
		lineageTag: 5afd2f55-805c-455b-8b46-152f979f109e
		summarizeBy: none
		sourceColumn: RiskReasons

	column CreatedDate
		dataType: dateTime
		isHidden
		formatString: yyyy-mm-dd
		lineageTag: c9819aff-941a-498f-9ede-bf11522f2761
		summarizeBy: none
		sourceColumn: CreatedDate

		annotation UnderlyingDateTimeDataType = Date

	column LastUsedDate
		dataType: dateTime
		isHidden
		formatString: yyyy-mm-dd
		lineageTag: b097d5f9-ffcd-4b0e-8483-68c3dc112efe
		summarizeBy: none
		sourceColumn: LastUsedDate

		annotation UnderlyingDateTimeDataType = Date

	/// What kind of principal owns the agent. Agents whose owner id does not resolve to a directory object - deleted users, cross-tenant guests, or system identities Graph will not return - are labelled rather than left blank.
	column OwnerPrincipalType = VAR p = RELATED ( 'User'[PrincipalType] ) RETURN IF ( ISBLANK ( p ) || p = "", "Not resolved in Entra", p )
		dataType: string
		lineageTag: 32a87696-6cb1-435a-afd6-f5daec977b45
		summarizeBy: none

	/// Whether a person authored the agent, the platform provisioned it automatically, or no creator was recorded at all. Most tenants are dominated by platform-provisioned agents - default environment scaffolding, template copies and system bots - which drown out real human activity, so this is offered as a slicer on every page. Note that an unresolved creator arrives as an empty string rather than BLANK, so both must be tested.
	column AgentOrigin = VAR creator = 'Agent'[CreatedByName] RETURN IF ( ISBLANK ( creator ) || creator = "", "Creator unknown", IF ( creator = "System / platform", "Platform-provisioned", "Human-built" ) )
		dataType: string
		lineageTag: cbe820c3-3e26-4051-a3af-893eb81916d0
		summarizeBy: none

	/// The agent's own Entra identity, shown in the Agent 365 registry as "Entra agent ID". This is not the same value as EntraAppId, which is the app registration behind the agent.
	column EntraAgentId
		dataType: string
		lineageTag: 5c1f8a02-7d43-4b96-9e21-a4c6f0b17d38
		summarizeBy: none
		sourceColumn: EntraAgentId

	/// Identifies the blueprint an agent was instantiated from, so sibling agents built from the same Microsoft template can be grouped.
	column EntraAgentBlueprintId
		dataType: string
		isHidden
		lineageTag: 9b3e47d1-06fa-4c58-8d77-2e5b91cc4a60
		summarizeBy: none
		sourceColumn: EntraAgentBlueprintId

	/// Runtime harness the agent was built on, e.g. Standard or the GitHub Copilot harness. Only populated for agents where the choice applies.
	column Harness
		dataType: string
		lineageTag: 2a8d6f34-b1e7-4029-95c3-70df8e4a1b52
		summarizeBy: none
		sourceColumn: Harness

	/// Length of the agent's instructions. Azure Resource Graph exposes the character count but not the instruction text itself, so this stands in as a "has instructions" signal and a rough measure of prompt complexity.
	column InstructionsCharCount
		dataType: int64
		formatString: #,0
		lineageTag: 7e04c9b8-5a12-43df-8b66-c1907f2e5d84
		summarizeBy: sum
		sourceColumn: InstructionsCharCount

	column GraphConnectorCount
		dataType: int64
		formatString: #,0
		lineageTag: 3f6b25ac-8e90-41d7-a4f2-6db8c0937e15
		summarizeBy: sum
		sourceColumn: GraphConnectorCount

	column SharePointSiteCount
		dataType: int64
		formatString: #,0
		lineageTag: c85a1730-42fb-4e6c-9038-b7e2f5641da9
		summarizeBy: sum
		sourceColumn: SharePointSiteCount

	column PublicSiteCount
		dataType: int64
		formatString: #,0
		lineageTag: 1d9c6e58-73a4-4b20-8f51-9a0e3c85b7f6
		summarizeBy: sum
		sourceColumn: PublicSiteCount

	column FileKnowledgeCount
		dataType: int64
		formatString: #,0
		lineageTag: 68b0f412-9d37-45ea-b1c8-4f52a7e09361
		summarizeBy: sum
		sourceColumn: FileKnowledgeCount

	column DataverseSourceCount
		dataType: int64
		formatString: #,0
		lineageTag: a47e8d95-2c61-4f38-90b7-5e13c6802fb4
		summarizeBy: sum
		sourceColumn: DataverseSourceCount

	/// Semicolon-separated list of the knowledge source kinds attached to the agent, e.g. "sharepointSites; graphConnectors". Absent kinds mean a count of zero.
	column KnowledgeTypes
		dataType: string
		lineageTag: b2705fc6-1a83-4d59-8e04-c93f6b17520d
		summarizeBy: none
		sourceColumn: KnowledgeTypes

	/// When the agent was quarantined. Blank unless IsQuarantined is true.
	column QuarantinedAt
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: 9c4e1a72-5b30-4d68-91af-2e7c6d0b8f41
		summarizeBy: none
		sourceColumn: QuarantinedAt

	/// Whether the agent carries any instruction text at all.
	column HasInstructions = 'Agent'[InstructionsCharCount] > 0
		dataType: boolean
		lineageTag: 2f8b60d4-c197-4a53-b7e2-58d9c4a10e6b
		summarizeBy: none

	/// Number of distinct knowledge kinds attached, derived from KnowledgeTypes.
	column KnowledgeTypeCount = IF ( ISBLANK ( 'Agent'[KnowledgeTypes] ) || 'Agent'[KnowledgeTypes] = "", 0, PATHLENGTH ( SUBSTITUTE ( 'Agent'[KnowledgeTypes], "; ", "|" ) ) )
		dataType: int64
		formatString: #,0
		lineageTag: 6a3d92e8-40bc-4f17-8e5a-b1c72f9d3054
		summarizeBy: sum

	/// Most recent evidence the agent ran, taking the later of the Power Platform usage record and the last audit-log interaction.
	/// Deliberately avoids CALCULATE. Context transition inside a calculated column takes a dependency on every column of its own table, and DaysSinceLastActivity and ActivityStatus both depend on this one - so CALCULATE ( MAX ( 'Interaction'[CreationTime] ) ) is circular here and silently evaluates to blank, reporting agents with real interactions as unused. MAXX over an explicit FILTER depends only on Agent[AgentKey], so it resolves.
	column LastActivityAt = VAR ArgUse = 'Agent'[LastUsed] VAR K = 'Agent'[AgentKey] VAR Audit = MAXX ( FILTER ( 'Interaction', 'Interaction'[AgentKey] = K ), 'Interaction'[CreationTime] ) RETURN IF ( ISBLANK ( ArgUse ), Audit, IF ( ISBLANK ( Audit ), ArgUse, MAX ( ArgUse, Audit ) ) )
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: 4d81c0a6-7e35-4b92-9f10-3ac6b25e7d18
		summarizeBy: none

	/// Days since the agent last ran, from either source.
	column DaysSinceLastActivity = IF ( ISBLANK ( 'Agent'[LastActivityAt] ), BLANK ( ), DATEDIFF ( 'Agent'[LastActivityAt], TODAY ( ), DAY ) )
		dataType: int64
		formatString: #,0
		lineageTag: 8b25f7c1-3d64-4e08-a6b9-71e05c8f42da
		summarizeBy: sum

	/// Activity from both the Power Platform usage record and the audit log, so an agent with real interactions is never reported as unused.
	column ActivityStatus = VAR D = 'Agent'[DaysSinceLastActivity] RETURN IF ( ISBLANK ( D ), "No usage signal", IF ( D <= 7, "Active (7d)", IF ( D <= 30, "Active (30d)", IF ( D <= 90, "Idle (90d)", "Dormant (90d+)" ) ) ) )
		dataType: string
		lineageTag: e70a4b39-16cd-42f5-8b7e-9d3f06a1c825
		summarizeBy: none

	/// Groups agents the way the Agent 365 registry does, separating what the organisation built from what Microsoft ships pre-installed.
	column CreatorCategory = VAR blueprint = 'Agent'[EntraAgentBlueprintId] VAR creator = 'Agent'[CreatedByName] RETURN IF ( 'Agent'[IsManaged] && ( ISBLANK ( creator ) || creator = "System / platform" ), "Microsoft", IF ( ISBLANK ( creator ) || creator = "", "Unattributed", IF ( NOT ISBLANK ( blueprint ) && blueprint <> "", "Built from Microsoft blueprint", "Your organization" ) ) )
		dataType: string
		lineageTag: 4c19e7b3-8fa5-462d-b730-0d85916ecf27
		summarizeBy: none

	/// True when the agent reads from at least one Microsoft Graph connector, which widens its reach to indexed third-party content.
	column HasGraphConnector = 'Agent'[GraphConnectorCount] > 0
		dataType: boolean
		lineageTag: e93b04f7-6d21-458a-9c16-2b7048af35e1
		summarizeBy: none

	/// Ownerless agents are the ones nobody can be asked to review, so the registry calls them out separately.
	column HasOwner = NOT ( ISBLANK ( 'Agent'[OwnerName] ) || 'Agent'[OwnerName] = "" )
		dataType: boolean
		lineageTag: 0a6f2d84-b957-43ce-81e2-5f4c7093ba16
		summarizeBy: none

	partition Agent = m
		mode: import
		source =
				let
				    RawAgents = FnArg("PowerPlatformResources | where type =~ 'microsoft.copilotstudio/agents' | extend p = properties | extend cc = p.componentsCounts, cap = p.capabilitiesCounts, sv = p.sharedWithViewers, se = p.sharedWithEditors | extend kbt = cc.knowledgeByType | project AgentKey = strcat(tostring(p.environmentId), '|', tostring(name)), AgentId = tostring(name), AgentName = tostring(p.displayName), AuthoringSurface = tostring(p.createdIn), EnvironmentId = tostring(p.environmentId), Region = tostring(location), SchemaName = tostring(p.schemaName), Orchestration = tostring(p.orchestration), Model = tostring(p.model), Authentication = tostring(p.authentication), CreatedAt = tostring(p.createdAt), LastPublishedAt = tostring(p.lastPublishedAt), IsQuarantined = tobool(p.isQuarantined), IsManaged = tobool(p.isManaged), IsGithubCopilotAgent = tobool(p.isGithubCopilotAgent), IsCLIAgent = tobool(p.isCLIAgent), WebSearchEnabled = tobool(p.isWebSearchEnabledForKnowledge), Channels = strcat_array(p.channels, '; '), ChannelCount = coalesce(array_length(p.channels), 0), TopicCount = toint(cc.topics), ToolCount = toint(cc.tools), KnowledgeCount = toint(cc.knowledge), ConnectedAgentCount = toint(cc.connectedAgents), ConnectorCount = toint(cap.distinctPowerPlatformConnectors), ConnectorOpsCount = toint(cap.distinctPowerPlatformConnectorsOperations), FlowCount = toint(cap.distinctFlows), SharedUserCount = toint(sv.userCount), SharedGroupCount = toint(sv.groupCount), SharedTenantWide = tobool(sv.entireTenant), EditorUserCount = toint(se.userCount), OwnerId = tostring(p.ownerId), CreatedBy = tostring(p.createdBy), EntraAppId = tostring(p.entraAppId), TitleId = tostring(p.titleId), QuarantinedAt = tostring(p.quarantinedAt), EntraAgentId = tostring(p.entraAgentId), EntraAgentBlueprintId = tostring(p.entraAgentBlueprintId), Harness = tostring(p.harness), InstructionsCharCount = coalesce(toint(p.instructionsCharactersCount), 0), GraphConnectorCount = coalesce(toint(kbt.graphConnectors), 0), SharePointSiteCount = coalesce(toint(kbt.sharepointSites), 0), PublicSiteCount = coalesce(toint(kbt.publicSites), 0), FileKnowledgeCount = coalesce(toint(kbt.files), 0), DataverseSourceCount = coalesce(toint(kbt.dataverseSources), 0), KnowledgeTypes = strcat_array(bag_keys(kbt), '; ') | order by AgentKey asc"),
				    RawUsage = FnArg("PowerPlatformResources | where type =~ 'microsoft.powerplatformusage/usagerecords' | where isnotnull(properties) | project ResourceKey = tostring(properties.resourceId), LastUsedRaw = tostring(properties.lastUsed) | where isnotempty(ResourceKey) and isnotempty(LastUsedRaw) | summarize LastUsedRaw = max(LastUsedRaw) by ResourceKey | order by ResourceKey asc"),
				    RawEnvs = FnArg("PowerPlatformResources | where type =~ 'microsoft.powerplatform/environments' | extend p = properties | project EnvironmentId = tostring(name), EnvironmentName = tostring(p.displayName), Region = tostring(location), EnvironmentType = tostring(p.environmentType), IsManaged = tobool(p.isManaged), EnvironmentGroupId = tostring(p.environmentGroupId), CreatedAt = tostring(p.createdAt), LastModifiedAt = tostring(p.lastModifiedAt), CreatedBy = tostring(p.createdBy) | order by EnvironmentId asc"),
				    tAgents = FnRecordsToTable(RawAgents, {"AgentKey", "AgentId", "AgentName", "AuthoringSurface", "EnvironmentId", "Region", "SchemaName", "Orchestration", "Model", "Authentication", "CreatedAt", "LastPublishedAt", "IsQuarantined", "IsManaged", "IsGithubCopilotAgent", "IsCLIAgent", "WebSearchEnabled", "Channels", "ChannelCount", "TopicCount", "ToolCount", "KnowledgeCount", "ConnectedAgentCount", "ConnectorCount", "ConnectorOpsCount", "FlowCount", "SharedUserCount", "SharedGroupCount", "SharedTenantWide", "EditorUserCount", "OwnerId", "CreatedBy", "EntraAppId", "TitleId", "QuarantinedAt", "EntraAgentId", "EntraAgentBlueprintId", "Harness", "InstructionsCharCount", "GraphConnectorCount", "SharePointSiteCount", "PublicSiteCount", "FileKnowledgeCount", "DataverseSourceCount", "KnowledgeTypes"}),
				    tUsage = FnRecordsToTable(RawUsage, {"ResourceKey", "LastUsedRaw"}),
				    tEnvs = FnRecordsToTable(RawEnvs, {"EnvironmentId", "EnvironmentName", "EnvironmentType"}),
				    JoinUsage = Table.NestedJoin(tAgents, {"AgentId"}, tUsage, {"ResourceKey"}, "u", JoinKind.LeftOuter),
				    ExpUsage = Table.ExpandTableColumn(JoinUsage, "u", {"LastUsedRaw"}, {"LastUsedRaw"}),
				    JoinEnv = Table.NestedJoin(ExpUsage, {"EnvironmentId"}, tEnvs, {"EnvironmentId"}, "e", JoinKind.LeftOuter),
				    ExpEnv = Table.ExpandTableColumn(JoinEnv, "e", {"EnvironmentName", "EnvironmentType"}, {"EnvironmentName", "EnvironmentType"}),
				    FillEnv = Table.ReplaceValue(ExpEnv, each [EnvironmentName], each if [EnvironmentName] = null or [EnvironmentName] = "" then "Unlisted: " & [EnvironmentId] else [EnvironmentName], Replacer.ReplaceValue, {"EnvironmentName"}),
				    FillEnvType = Table.ReplaceValue(FillEnv, each [EnvironmentType], each if [EnvironmentType] = null or [EnvironmentType] = "" then "Unknown" else [EnvironmentType], Replacer.ReplaceValue, {"EnvironmentType"}),
				    FillModel = Table.ReplaceValue(FillEnvType, each [Model], each if [Model] = null or [Model] = "" then "Not specified" else [Model], Replacer.ReplaceValue, {"Model"}),
				    Converted = Table.TransformColumns(FillModel, {{"CreatedAt", FnToDateTime, type datetime}, {"LastPublishedAt", FnToDateTime, type datetime}, {"LastUsedRaw", FnToDateTime, type datetime}, {"QuarantinedAt", FnToDateTime, type datetime}}),
				    Bools = Table.TransformColumns(Converted, {{"IsQuarantined", FnToLogical, type logical}, {"IsManaged", FnToLogical, type logical}, {"IsGithubCopilotAgent", FnToLogical, type logical}, {"IsCLIAgent", FnToLogical, type logical}, {"WebSearchEnabled", FnToLogical, type logical}, {"SharedTenantWide", FnToLogical, type logical}}),
				    Renamed = Table.RenameColumns(Bools, {{"LastUsedRaw", "LastUsed"}}),
				    Typed = Table.TransformColumnTypes(Renamed, {{"EnvironmentName", type text}, {"EnvironmentType", type text}}),
				    RawFoundry = FnArg("resources | where type startswith 'microsoft.cognitiveservices' or type startswith 'microsoft.machinelearningservices' | where (type endswith 'accounts/projects') or (tostring(kind) == 'Project') | extend p = properties | project AgentKey = tostring(id), AgentId = tostring(id), AgentName = tostring(split(name, '/')[-1]), EnvironmentId = tostring(subscriptionId), EnvironmentName = iff(name has '/', tostring(split(name, '/')[0]), tostring(name)), Region = tostring(location), CreatedAt = tostring(p.createdAtDate) | order by AgentKey asc"),
				    FoundryRecords = List.Transform(RawFoundry, each [
				        AgentKey = Record.FieldOrDefault(_, "AgentKey", null),
				        AgentId = Record.FieldOrDefault(_, "AgentId", null),
				        AgentName = Record.FieldOrDefault(_, "AgentName", null),
				        AuthoringSurface = "Azure AI Foundry",
				        EnvironmentId = Record.FieldOrDefault(_, "EnvironmentId", null),
				        Region = Record.FieldOrDefault(_, "Region", null),
				        SchemaName = null,
				        Orchestration = "Generative",
				        Model = "See deployments",
				        Authentication = "Microsoft Entra",
				        CreatedAt = FnToDateTime(Record.FieldOrDefault(_, "CreatedAt", null)),
				        LastPublishedAt = null,
				        IsQuarantined = false,
				        IsManaged = true,
				        IsGithubCopilotAgent = false,
				        IsCLIAgent = false,
				        WebSearchEnabled = false,
				        Channels = "API / SDK",
				        ChannelCount = 1,
				        TopicCount = 0,
				        ToolCount = 0,
				        KnowledgeCount = 0,
				        ConnectedAgentCount = 0,
				        ConnectorCount = 0,
				        ConnectorOpsCount = 0,
				        FlowCount = 0,
				        SharedUserCount = 0,
				        SharedGroupCount = 0,
				        SharedTenantWide = false,
				        EditorUserCount = 0,
				        OwnerId = null,
				        CreatedBy = null,
				        EntraAppId = null,
				        TitleId = null,
				        QuarantinedAt = null,
				        EntraAgentId = null,
				        EntraAgentBlueprintId = null,
				        Harness = null,
				        InstructionsCharCount = 0,
				        GraphConnectorCount = 0,
				        SharePointSiteCount = 0,
				        PublicSiteCount = 0,
				        FileKnowledgeCount = 0,
				        DataverseSourceCount = 0,
				        KnowledgeTypes = null,
				        LastUsed = null,
				        EnvironmentName = Record.FieldOrDefault(_, "EnvironmentName", null),
				        EnvironmentType = "Azure subscription"
				    ]),
				    tFoundry = FnRecordsToTable(FoundryRecords, {"AgentKey", "AgentId", "AgentName", "AuthoringSurface", "EnvironmentId", "Region", "SchemaName", "Orchestration", "Model", "Authentication", "CreatedAt", "LastPublishedAt", "IsQuarantined", "IsManaged", "IsGithubCopilotAgent", "IsCLIAgent", "WebSearchEnabled", "Channels", "ChannelCount", "TopicCount", "ToolCount", "KnowledgeCount", "ConnectedAgentCount", "ConnectorCount", "ConnectorOpsCount", "FlowCount", "SharedUserCount", "SharedGroupCount", "SharedTenantWide", "EditorUserCount", "OwnerId", "CreatedBy", "EntraAppId", "TitleId", "QuarantinedAt", "EntraAgentId", "EntraAgentBlueprintId", "Harness", "InstructionsCharCount", "GraphConnectorCount", "SharePointSiteCount", "PublicSiteCount", "FileKnowledgeCount", "DataverseSourceCount", "KnowledgeTypes", "LastUsed", "EnvironmentName", "EnvironmentType"}),
				    Combined = Table.Combine({Typed, tFoundry}),
				    Unified = FnDistinctKey(Combined, "AgentKey"),
				    Today = DateTime.LocalNow(),
				    WithPlatform = Table.AddColumn(Unified, "Platform", each
				        if [AuthoringSurface] = "Copilot Studio Lite" then "M365 Copilot Agent Builder"
				        else if [AuthoringSurface] = null or [AuthoringSurface] = "" then "Copilot Studio"
				        else [AuthoringSurface], type text),
				    WithPub = Table.AddColumn(WithPlatform, "IsPublished", each [LastPublishedAt] <> null, type logical),
				    WithDays = Table.AddColumn(WithPub, "DaysSinceLastUse", each if [LastUsed] = null then null else Duration.Days(Today - [LastUsed]), Int64.Type),
				    WithAge = Table.AddColumn(WithDays, "AgeDays", each if [CreatedAt] = null then null else Duration.Days(Today - [CreatedAt]), Int64.Type),
				    WithMonth = Table.AddColumn(WithAge, "CreatedMonth", each if [CreatedAt] = null then null else Date.ToText(DateTime.Date([CreatedAt]), "yyyy-MM"), type text),
				    WithStatus = Table.AddColumn(WithMonth, "ActivityStatus", each
				        if [DaysSinceLastUse] = null then "No usage signal"
				        else if [DaysSinceLastUse] <= 7 then "Active (7d)"
				        else if [DaysSinceLastUse] <= 30 then "Active (30d)"
				        else if [DaysSinceLastUse] <= 90 then "Idle (90d)"
				        else "Dormant (90d+)", type text),
				    WithRiskList = Table.AddColumn(WithStatus, "RiskFactorList", each List.RemoveNulls({
				        (if [Authentication] = null or [Authentication] = "" or [Authentication] = "None" or [Authentication] = "No authentication" then "No authentication configured (+3)" else null),
				        (if [IsQuarantined] = true then "Agent is quarantined (+3)" else null),
				        (if [SharedTenantWide] = true then "Shared with the entire tenant (+2)" else null),
				        (if [SharedTenantWide] = true and [LastUsed] = null then "Shared tenant-wide and never used (+1)" else null),
				        (if [WebSearchEnabled] = true then "Web search enabled on knowledge (+1)" else null),
				        (if [ConnectorCount] <> null and [ConnectorCount] > 0 then "Uses one or more connectors (+1)" else null),
				        (if [ConnectedAgentCount] <> null and [ConnectedAgentCount] > 0 then "Connected to other agents (+1)" else null)
				    }), type list),
				    WithReasons = Table.AddColumn(WithRiskList, "RiskReasons", each if List.Count([RiskFactorList]) = 0 then "No risk factors detected" else Text.Combine([RiskFactorList], "; "), type text),
				    WithFactorCount = Table.AddColumn(WithReasons, "RiskFactorCount", each List.Count([RiskFactorList]), Int64.Type),
				    WithRisk = Table.AddColumn(WithFactorCount, "RiskScore", each
				        (if [SharedTenantWide] = true then 2 else 0)
				        + (if [IsQuarantined] = true then 3 else 0)
				        + (if [Authentication] = null or [Authentication] = "" or [Authentication] = "None" or [Authentication] = "No authentication" then 3 else 0)
				        + (if [WebSearchEnabled] = true then 1 else 0)
				        + (if [ConnectorCount] <> null and [ConnectorCount] > 0 then 1 else 0)
				        + (if [ConnectedAgentCount] <> null and [ConnectedAgentCount] > 0 then 1 else 0)
				        + (if [SharedTenantWide] = true and [LastUsed] = null then 1 else 0), Int64.Type),
				    WithBand = Table.AddColumn(WithRisk, "RiskBand", each if [RiskScore] >= 5 then "High" else if [RiskScore] >= 3 then "Medium" else "Low", type text),
				    Ordered = Table.SelectColumns(WithBand, {"AgentKey", "AgentId", "AgentName", "Platform", "AuthoringSurface", "EnvironmentId", "EnvironmentName", "EnvironmentType", "Region", "SchemaName", "Orchestration", "Model", "Authentication", "CreatedAt", "LastPublishedAt", "LastUsed", "IsPublished", "IsQuarantined", "IsManaged", "IsGithubCopilotAgent", "IsCLIAgent", "WebSearchEnabled", "Channels", "ChannelCount", "TopicCount", "ToolCount", "KnowledgeCount", "ConnectedAgentCount", "ConnectorCount", "ConnectorOpsCount", "FlowCount", "SharedUserCount", "SharedGroupCount", "SharedTenantWide", "EditorUserCount", "OwnerId", "CreatedBy", "EntraAppId", "TitleId", "QuarantinedAt", "EntraAgentId", "EntraAgentBlueprintId", "Harness", "KnowledgeTypes", "InstructionsCharCount", "GraphConnectorCount", "SharePointSiteCount", "PublicSiteCount", "FileKnowledgeCount", "DataverseSourceCount", "DaysSinceLastUse", "AgeDays", "CreatedMonth", "ActivityStatus", "RiskScore", "RiskBand", "RiskFactorCount", "RiskReasons"}, MissingField.UseNull),
				    Retyped = Table.TransformColumnTypes(Ordered, {{"AgentKey", type text}, {"AgentId", type text}, {"AgentName", type text}, {"Platform", type text}, {"AuthoringSurface", type text}, {"EnvironmentId", type text}, {"EnvironmentName", type text}, {"EnvironmentType", type text}, {"Region", type text}, {"SchemaName", type text}, {"Orchestration", type text}, {"Model", type text}, {"Authentication", type text}, {"CreatedAt", type datetime}, {"LastPublishedAt", type datetime}, {"LastUsed", type datetime}, {"IsPublished", type logical}, {"IsQuarantined", type logical}, {"IsManaged", type logical}, {"IsGithubCopilotAgent", type logical}, {"IsCLIAgent", type logical}, {"WebSearchEnabled", type logical}, {"Channels", type text}, {"ChannelCount", Int64.Type}, {"TopicCount", Int64.Type}, {"ToolCount", Int64.Type}, {"KnowledgeCount", Int64.Type}, {"ConnectedAgentCount", Int64.Type}, {"ConnectorCount", Int64.Type}, {"ConnectorOpsCount", Int64.Type}, {"FlowCount", Int64.Type}, {"SharedUserCount", Int64.Type}, {"SharedGroupCount", Int64.Type}, {"SharedTenantWide", type logical}, {"EditorUserCount", Int64.Type}, {"OwnerId", type text}, {"CreatedBy", type text}, {"EntraAppId", type text}, {"TitleId", type text}, {"QuarantinedAt", type datetime}, {"EntraAgentId", type text}, {"EntraAgentBlueprintId", type text}, {"Harness", type text}, {"KnowledgeTypes", type text}, {"InstructionsCharCount", Int64.Type}, {"GraphConnectorCount", Int64.Type}, {"SharePointSiteCount", Int64.Type}, {"PublicSiteCount", Int64.Type}, {"FileKnowledgeCount", Int64.Type}, {"DataverseSourceCount", Int64.Type}, {"DaysSinceLastUse", Int64.Type}, {"AgeDays", Int64.Type}, {"CreatedMonth", type text}, {"ActivityStatus", type text}, {"RiskScore", Int64.Type}, {"RiskBand", type text}, {"RiskFactorCount", Int64.Type}, {"RiskReasons", type text}}),
				    WithCreatedDate = Table.AddColumn(Retyped, "CreatedDate", each if [CreatedAt] = null then null else DateTime.Date([CreatedAt]), type date),
				    WithLastUsedDate = Table.AddColumn(WithCreatedDate, "LastUsedDate", each if [LastUsed] = null then null else DateTime.Date([LastUsed]), type date)
				in
				    WithLastUsedDate

	annotation PBI_ResultType = Table

