/// Every distinct AppIdentity seen in the Purview audit log, classified by surface type and joined to the agent inventory where possible.
table CopilotSurface
	lineageTag: 5a873a5d-088f-4e0f-884e-9d763fbfc087

	column SurfaceKey
		dataType: string
		isHidden
		lineageTag: 3fd9e8bd-3911-4bfe-a81f-dfa8633b3e4e
		summarizeBy: none
		sourceColumn: SurfaceKey

	/// Raw AppIdentity value from the audit record.
	column AppIdentity
		dataType: string
		lineageTag: b325e624-fcd3-49cd-85e2-09d914bac18c
		summarizeBy: none
		sourceColumn: AppIdentity

	/// Friendly name - the agent's display name where the surface resolved to an inventory agent.
	column SurfaceName
		dataType: string
		lineageTag: 8fa3ed79-6219-4204-98f6-4026d123935b
		summarizeBy: none
		sourceColumn: SurfaceName

	/// Agent Builder agent / Copilot Studio agent / Custom engine agent / M365 Copilot (base) / Microsoft 1P agent / Fabric copilot.
	column SurfaceType
		dataType: string
		lineageTag: d4eb44d3-8b72-4b19-874f-7051b130853e
		summarizeBy: none
		sourceColumn: SurfaceType

	column Platform
		dataType: string
		lineageTag: 3465e7ce-f7e9-4dba-8125-1f908aff7a11
		summarizeBy: none
		sourceColumn: Platform

	/// TRUE when the surface is a specific agent rather than a base Copilot experience.
	column IsAgent
		dataType: string
		lineageTag: a2092e1e-9ee4-47ba-a01b-629372e09da5
		summarizeBy: none
		sourceColumn: IsAgent

		annotation SummarizationSetBy = Automatic

	column AgentKey
		dataType: string
		isHidden
		lineageTag: fef0126b-43f4-4baa-aeec-e583d8ee5621
		summarizeBy: none
		sourceColumn: AgentKey

	column AgentName
		dataType: string
		lineageTag: f4f74535-929e-4f56-85ac-d50c19d9cea2
		summarizeBy: none
		sourceColumn: AgentName

	/// Which key joined the audit surface to the inventory: TitleId or SchemaName.
	column MatchOn
		dataType: string
		lineageTag: fce3bd07-1381-41ca-8300-bacfe93c08e0
		summarizeBy: none
		sourceColumn: MatchOn

	/// TRUE when the surface was found in the agent inventory.
	column IsMatched
		dataType: boolean
		lineageTag: e5bfebc3-89e0-4c20-bebd-d64a5b660e67
		summarizeBy: none
		sourceColumn: IsMatched

	/// For a SharePoint agent, the site collection the .agent file lives in. Blank for every other surface.
	column SharePointSiteId
		dataType: string
		lineageTag: 6b1c9e04-58af-4d27-9a3e-11d7c5b8e2f0
		summarizeBy: none
		sourceColumn: SharePointSiteId

	/// For a SharePoint agent, the document library item id of the .agent file. Blank for every other surface.
	column SharePointItemId
		dataType: string
		lineageTag: 0d8e37b5-c14a-4f96-83b2-4ee6a9017c3d
		summarizeBy: none
		sourceColumn: SharePointItemId

	column SharePointWebId
		dataType: string
		lineageTag: c14eb563-5857-4dbc-aa64-89528796b76f
		summarizeBy: none
		sourceColumn: SharePointWebId

	column SharePointListId
		dataType: string
		lineageTag: 15c925fb-6168-48b5-8248-b62aed895bea
		summarizeBy: none
		sourceColumn: SharePointListId

	/// ListItemUniqueId decoded from the opaque SharePoint drive-item id. This is the exact join key to SharePointAgent.
	column SharePointItemGuid
		dataType: string
		lineageTag: e457965a-cecb-4185-ad3b-236de16ce2ef
		summarizeBy: none
		sourceColumn: SharePointItemGuid

	column SharePointAgentKey
		dataType: string
		isHidden
		lineageTag: f5d60ca3-34cf-4744-8db4-904432837def
		summarizeBy: none
		sourceColumn: SharePointAgentKey

	column SharePointAgentName
		dataType: string
		lineageTag: 6d838cf5-f021-4cf7-acbb-a1a9ed2e0960
		summarizeBy: none
		sourceColumn: SharePointAgentName

	column SharePointSiteUrl
		dataType: string
		lineageTag: 0a2abf18-6a8c-48f6-93f7-730c1f3abeb9
		summarizeBy: none
		sourceColumn: SharePointSiteUrl

	column SharePointObjectUrl
		dataType: string
		lineageTag: b02b65ac-3534-4c95-aa70-5ea8e1989226
		summarizeBy: none
		sourceColumn: SharePointObjectUrl

	column SharePointIsDeleted
		dataType: boolean
		lineageTag: e4b4494f-3c1d-4f96-b614-45bbf63450ca
		summarizeBy: none
		sourceColumn: SharePointIsDeleted

	partition CopilotSurface = m
		mode: import
		source =
				let
				    Src = SrcSurfaceKey,
				    Ren = Table.RenameColumns(Src, {{"poc_appidentity", "SurfaceKey"}}),
				    Norm = Table.TransformColumns(Ren, {{"SurfaceKey", each if _ = null then "" else _, type text}}),
				    Keys = FnDistinctKey(Norm, "SurfaceKey"),
				    Classified = Table.AddColumn(Keys, "s", each FnSurface([SurfaceKey])),
				    Exp = Table.ExpandRecordColumn(Classified, "s", {"SurfaceType", "Platform", "MatchKey", "MatchOn", "DisplayName", "IsAgent"}),
				    Indexed = Table.AddColumn(Exp, "MatchIndex", each
				        if [IsAgent] and [MatchKey] <> "" then [MatchOn] & "|" & Text.Lower([MatchKey]) else null, type text),
				    Joined = Table.NestedJoin(Indexed, {"MatchIndex"}, FnAgentLookup(), {"MatchIndex"}, "agent", JoinKind.LeftOuter),
				    Agented = Table.ExpandTableColumn(Joined, "agent", {"AgentKey", "AgentName"}, {"AgentKey", "AgentName"}),
				    Filled = Table.TransformColumns(Agented, {
				        {"AgentKey", each if _ = null then "" else _, type text},
				        {"AgentName", each if _ = null then "" else _, type text}}),
				    WithId = Table.AddColumn(Filled, "AppIdentity", each [SurfaceKey], type text),
				    WithSpo = Table.AddColumn(WithId, "spo", each FnSpo([SurfaceKey])),
				    SpoExp = Table.ExpandRecordColumn(WithSpo, "spo", {"SiteId", "WebId", "ListId", "ItemId", "ItemGuid"}, {"SharePointSiteId", "SharePointWebId", "SharePointListId", "SharePointItemId", "SharePointItemGuid"}),
				    SpoKeyed = Table.AddColumn(SpoExp, "SharePointAgentKey", each Text.Lower([SharePointItemGuid]), type text),
				    SpoJoined = Table.NestedJoin(SpoKeyed, {"SharePointAgentKey"}, FnSharePointAgentLookup(), {"AgentKey"}, "spAgent", JoinKind.LeftOuter),
				    SpoAgented = Table.ExpandTableColumn(SpoJoined, "spAgent", {"AgentKey", "AgentName", "SiteUrl", "ObjectUrl", "IsDeleted"}, {"MatchedSharePointAgentKey", "SharePointAgentName", "SharePointSiteUrl", "SharePointObjectUrl", "SharePointIsDeleted"}),
				    SpoFilled = Table.TransformColumns(SpoAgented, {
				        {"MatchedSharePointAgentKey", each if _ = null then "" else _, type text},
				        {"SharePointAgentName", each if _ = null then "" else _, type text},
				        {"SharePointSiteUrl", each if _ = null then "" else _, type text},
				        {"SharePointObjectUrl", each if _ = null then "" else _, type text}}),
				    // Where a surface resolves to either inventory its real display name wins over
				    // the audit feed's own label, which is often a bare app id.
				    WithName = Table.AddColumn(SpoFilled, "SurfaceName", each if [SharePointAgentName] <> "" then [SharePointAgentName] else if [AgentName] <> "" then [AgentName] else [DisplayName], type text),
				    WithMatched = Table.AddColumn(WithName, "IsMatched", each [AgentKey] <> "" or [MatchedSharePointAgentKey] <> "", type logical),
				    Kept = Table.SelectColumns(WithMatched, {"SurfaceKey", "AppIdentity", "SurfaceName", "SurfaceType", "Platform", "IsAgent", "AgentKey", "AgentName", "MatchOn", "IsMatched", "SharePointSiteId", "SharePointWebId", "SharePointListId", "SharePointItemId", "SharePointItemGuid", "SharePointAgentKey", "SharePointAgentName", "SharePointSiteUrl", "SharePointObjectUrl", "SharePointIsDeleted"}, MissingField.UseNull),
				    Typed = Table.TransformColumnTypes(Kept, {
				        {"SurfaceKey", type text}, {"AppIdentity", type text}, {"SurfaceName", type text}, {"SurfaceType", type text},
				        {"Platform", type text}, {"AgentKey", type text}, {"AgentName", type text}, {"MatchOn", type text},
				        {"SharePointSiteId", type text}, {"SharePointWebId", type text}, {"SharePointListId", type text},
				        {"SharePointItemId", type text}, {"SharePointItemGuid", type text}, {"SharePointAgentKey", type text},
				        {"SharePointAgentName", type text}, {"SharePointSiteUrl", type text}, {"SharePointObjectUrl", type text},
				        {"SharePointIsDeleted", type logical}})
				in
				    Typed
