/// Contiguous date table generated in M from the DateStart parameter through the end of next month.
table Date
	lineageTag: 319da80c-c54c-408d-8154-6723f617e62e
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: yyyy-mm-dd
		lineageTag: 0dfa69f4-3425-436e-93fd-2dbb0e3ec502
		summarizeBy: none
		sourceColumn: Date

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 88139cab-e3c4-4e21-829f-68f554bc3dd2
		summarizeBy: sum
		sourceColumn: Year

	column Quarter
		dataType: string
		lineageTag: 5ef5f604-8b62-45e5-a2b2-b63a6aedab42
		summarizeBy: none
		sourceColumn: Quarter

	column MonthNo
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7d0b2851-d35d-40b1-95b1-2af5d41cdb70
		summarizeBy: sum
		sourceColumn: MonthNo

	column MonthName
		dataType: string
		lineageTag: 436e50cf-9261-48a9-a6f2-d17b7bc1f02f
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: MonthNo

	column YearMonth
		dataType: string
		lineageTag: 1965e287-9ac6-46f3-ad3b-93e1acb604d9
		summarizeBy: none
		sourceColumn: YearMonth

	column DayOfWeek
		dataType: string
		lineageTag: bf9237a3-2f29-447d-b631-c4dab878540f
		summarizeBy: none
		sourceColumn: DayOfWeek

	column IsWeekend
		dataType: boolean
		lineageTag: e93ce86c-7401-4979-b500-fc31cdd5bb65
		summarizeBy: none
		sourceColumn: IsWeekend

	partition Date = m
		mode: import
		source =
				let
				    Start = Date.From(DateStart),
				    Finish = Date.EndOfMonth(Date.AddMonths(Date.From(DateTimeZone.FixedUtcNow()), 1)),
				    Dates = List.Dates(Start, Duration.Days(Finish - Start) + 1, #duration(1, 0, 0, 0)),
				    T = Table.FromList(Dates, Splitter.SplitByNothing(), {"Date"}),
				    D = Table.TransformColumnTypes(T, {{"Date", type date}}),
				    Y = Table.AddColumn(D, "Year", each Date.Year([Date]), Int64.Type),
				    Q = Table.AddColumn(Y, "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date])), type text),
				    MN = Table.AddColumn(Q, "MonthNo", each Date.Month([Date]), Int64.Type),
				    MNm = Table.AddColumn(MN, "MonthName", each Date.MonthName([Date], "en-GB"), type text),
				    YM = Table.AddColumn(MNm, "YearMonth", each Text.From(Date.Year([Date])) & "-" & Text.PadStart(Text.From(Date.Month([Date])), 2, "0"), type text),
				    DW = Table.AddColumn(YM, "DayOfWeek", each Date.DayOfWeekName([Date], "en-GB"), type text),
				    WE = Table.AddColumn(DW, "IsWeekend", each Date.DayOfWeek([Date], Day.Monday) >= 5, type logical),
				    Kept = Table.SelectColumns(WE, {"Date", "Year", "Quarter", "MonthNo", "MonthName", "YearMonth", "DayOfWeek", "IsWeekend"}, MissingField.UseNull)
				in
				    Kept

