/// One row per Copilot turn from the Purview unified audit log. This is the only per-agent usage signal available for M365 Copilot Agent Builder agents.
table Interaction
	lineageTag: 4d5cad54-5190-4fd8-9a3a-beb3f5524663

	column Date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: cd5a5a5d-f808-4648-a39e-9a5fcd649e9f
		summarizeBy: none
		sourceColumn: Date

		annotation UnderlyingDateTimeDataType = Date

	column CreationTime
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: 9458f832-534f-4f1e-90ce-d346068a2250
		summarizeBy: none
		sourceColumn: CreationTime

	/// AppIdentity from the audit record - the join key to CopilotSurface.
	column SurfaceKey
		dataType: string
		isHidden
		lineageTag: 1d4b025a-af6a-4e2b-a3d9-32fe7eb64711
		summarizeBy: none
		sourceColumn: SurfaceKey

	/// Resolved inventory agent, blank when the surface is not an agent (base M365 Copilot, Microsoft first-party agents).
	column AgentKey
		dataType: string
		isHidden
		lineageTag: 0bd12d77-6f93-4032-8f2b-5e76516658ed
		summarizeBy: none
		sourceColumn: AgentKey

	/// The user who made the request.
	column UserPrincipalName
		dataType: string
		lineageTag: a875f63b-0d9a-4ec8-a110-2c3835e682ad
		summarizeBy: none
		sourceColumn: UserPrincipalName

	/// Client the interaction came from: Teams, Office, m365copilot, SharePoint, Copilot Studio, MCP, Autonomous...
	column AppHost
		dataType: string
		lineageTag: 460cd978-4ffa-4319-8bdb-85eaa206e0bd
		summarizeBy: none
		sourceColumn: AppHost

	column Operation
		dataType: string
		lineageTag: daaf3137-ee80-47f6-a4fa-fd16f56def2b
		summarizeBy: none
		sourceColumn: Operation

	/// Conversation identifier - use to count sessions rather than turns.
	column ThreadId
		dataType: string
		isHidden
		lineageTag: dc88c75e-cf95-4e9b-813d-fd1f11c2b5c3
		summarizeBy: none
		sourceColumn: ThreadId

	column MessageCount
		dataType: int64
		formatString: #,0
		lineageTag: 37ca1e08-dcee-4515-9c0d-47cf314e5fb2
		summarizeBy: sum
		sourceColumn: MessageCount

	/// How many files, sites, connectors or MCP tools the turn touched.
	column ResourceCount
		dataType: int64
		formatString: #,0
		lineageTag: cfd79297-d18b-49a5-b3d6-63dee9176899
		summarizeBy: sum
		sourceColumn: ResourceCount

	/// Names of the resources the turn accessed, as reported by CopilotEventData.AccessedResources.
	column Resources
		dataType: string
		lineageTag: fab3084f-4cc9-4156-832c-a060b91b2d99
		summarizeBy: none
		sourceColumn: Resources

	partition Interaction = m
		mode: import
		source =
				let
				    Src = SrcInteraction,
				    Ren = Table.RenameColumns(Src, {
				        {"poc_creationtime", "CreationTime"}, {"poc_appidentity", "SurfaceKey"}, {"poc_userid", "UserPrincipalName"},
				        {"poc_apphost", "AppHost"}, {"poc_operation", "Operation"}, {"poc_threadid", "ThreadId"},
				        {"poc_resourcecount", "ResourceCount"}, {"poc_resources", "Resources"}}),
				    // A null AppIdentity is a real surface (base M365 Copilot), so it has to carry the
				    // same empty-string key on both sides of the CopilotSurface relationship.
				    Keys = Table.TransformColumns(Ren, {{"SurfaceKey", each if _ = null then "" else _, type text}}),
				    Time = Table.TransformColumns(Keys, {{"CreationTime", each FnToDateTime(_), type datetime}}),
				    Dated = Table.AddColumn(Time, "Date", each if [CreationTime] = null then null else DateTime.Date([CreationTime]), type date),
				    Indexed = Table.AddColumn(Dated, "MatchIndex", each
				        let s = FnSurface([SurfaceKey]) in
				        if s[IsAgent] and s[MatchKey] <> "" then s[MatchOn] & "|" & Text.Lower(s[MatchKey]) else null, type text),
				    Joined = Table.NestedJoin(Indexed, {"MatchIndex"}, FnAgentLookup(), {"MatchIndex"}, "agent", JoinKind.LeftOuter),
				    Agented = Table.ExpandTableColumn(Joined, "agent", {"AgentKey"}, {"AgentKey"}),
				    Filled = Table.TransformColumns(Agented, {{"AgentKey", each if _ = null then "" else _, type text}}),
				    // CopilotEventData.MessageIds is always empty in the audit feed, so this stays zero
				    // and is retained only to keep the Interaction column contract stable.
				    Msgs = Table.AddColumn(Filled, "MessageCount", each 0, Int64.Type),
				    Kept = Table.SelectColumns(Msgs, {"Date", "CreationTime", "SurfaceKey", "AgentKey", "UserPrincipalName", "AppHost", "Operation", "ThreadId", "MessageCount", "ResourceCount", "Resources"}, MissingField.UseNull),
				    Typed = Table.TransformColumnTypes(Kept, {
				        {"SurfaceKey", type text}, {"AgentKey", type text}, {"UserPrincipalName", type text}, {"AppHost", type text},
				        {"Operation", type text}, {"ThreadId", type text}, {"Resources", type text}, {"ResourceCount", Int64.Type}})
				in
				    Typed

